"""Generate the native env/orders field lists from the JAX ``ModernState`` / ``ModernOrders`` pytrees.

Every leaf becomes one pointer field named after its path (``.combat.items.fighter.carve`` ->
``combat_items_fighter_carve``), in pytree order, followed by the native-only caches. The lists are X-macros
(``native/src/gen/{env,orders}_fields.inc``: ``X(ctype, name)``); shapes come from the world at runtime
(``native/python/lanesim.py``). Regenerate after changing the JAX state:

    python -m ops.native.gen_state
"""
from __future__ import annotations

import os
from pathlib import Path

import numpy as np

OUT = Path(__file__).resolve().parents[2] / "native" / "src" / "gen"
CTYPE = {"float32": "float", "int32": "int32_t", "uint32": "uint32_t", "bool": "uint8_t"}
# Native-only caches: (ctype, name, element count as a function of the world).
NATIVE = (("float", "memo_route"), ("int32_t", "memo_anchor"), ("int32_t", "ev_n"), ("int32_t", "ev_src"),
          ("int32_t", "ev_dst"), ("int32_t", "rec_n"), ("int32_t", "rec"))


def leaf_name(path: str) -> str:
    return path.lstrip(".").replace(".", "_")


def leaves(tree):
    import jax
    return [(leaf_name(jax.tree_util.keystr(p)), np.asarray(v)) for p, v in jax.tree_util.tree_flatten_with_path(tree)[0]]


def main() -> None:
    os.environ.setdefault("JAX_PLATFORMS", "cpu")
    from lanerl_jax.modern import world as MS
    from ops.modern.golden import build
    cfg = build("top")
    OUT.mkdir(parents=True, exist_ok=True)
    head = "// GENERATED by ops/native/gen_state.py from the JAX pytree: do not edit.\n"
    env = [f"X({CTYPE[str(v.dtype)]}, {name})  /* {v.dtype}{list(v.shape)} */" for name, v in leaves(MS.init_state(cfg))]
    env += [f"X({t}, {name})  /* native cache */" for t, name in NATIVE]
    (OUT / "env_fields.inc").write_text(head + "\n".join(env) + "\n")
    orders = [f"X({CTYPE[str(v.dtype)]}, {name})  /* {v.dtype}{list(v.shape)} */"
              for name, v in leaves(MS.no_orders())]
    (OUT / "orders_fields.inc").write_text(head + "\n".join(orders) + "\n")
    print(len(env), "env fields,", len(orders), "order fields")


if __name__ == "__main__":
    main()
