"""Generate native/src/champ/dispatch.cpp: the item and rune hook dispatch over the ported modules, in the JAX
``MODULES`` order with the same merge rules (items/effects/__init__.py, runes/effects/__init__.py).

Item modules run only if some holder can hold one of their items (COVERAGE + ACTIVE_ITEMS, ``_each``); rune
modules always run. Module hooks are ``lanesim::items::<module>::<hook>`` / ``lanesim::runes::<module>::<hook>``
with the JAX signatures (state by value, ``std::tuple`` results).

    python -m ops.native.gen_dispatch
"""
from __future__ import annotations

import os
from pathlib import Path

OUT = Path(__file__).resolve().parents[2] / "native" / "src" / "champ" / "dispatch.cpp"
EVENT = {"on_attack": ("const Attack& a", "a"), "on_hit": ("const Attack& a", "a"), "on_cast": ("const Cast& cast", "cast"),
         "on_cc": ("const CC& cc", "cc"), "on_damage": ("const Report& r", "r"), "periodic": ("", ""),
         "on_takedown": ("const Kills& k", "k")}


def main() -> None:
    os.environ.setdefault("JAX_PLATFORMS", "cpu")
    from lanerl_jax.modern.items import effects as IE
    from lanerl_jax.modern.runes import effects as RE
    items = [(m.__name__.rsplit(".", 1)[-1], m) for m in IE.MODULES]
    runes = [(m.__name__.rsplit(".", 1)[-1], m) for m in RE.MODULES]
    L = ["// GENERATED by ops/native/gen_dispatch.py: item and rune dispatch over the ported modules.",
         '#include "dispatch.hpp"', "", '#include "items/items.hpp"', '#include "items/items_b.hpp"',
         '#include "runes/runes.hpp"', '#include "stats.hpp"', "", "namespace lanesim::champ::items {", "",
         "namespace {",
         "// items.effects._each: some holder can hold one of the module's items.",
         "bool live(const Owned& own, const char* name) {",
         "    const auto& ids = data::table(std::string(\"dispatch.items.\") + name);",
         "    if (own.allowed.size() == 0) return true;",
         "    int ni = n_items();",
         "    size_t c = own.allowed.size() / ni;",
         "    for (float id : ids) {",
         "        if (id == 0.f) continue;",
         "        int r = item_row((int)id);",
         "        for (size_t h = 0; h < c; ++h)",
         "            if (own.allowed[h * ni + r]) return true;",
         "    }",
         "    return false;",
         "}",
         "}  // namespace", ""]
    hooks = lambda mods, h: [(n, m) for n, m in mods if hasattr(m, h)]           # noqa: E731
    ns = lambda n: f"::lanesim::items::{n}"                                       # noqa: E731

    # stats / defense / status / debuffs
    L += ["ItemStats dynamic_stats(const ItemEffectState& s, const Owned& own, const Ctx& ctx) {",
          "    ItemStats z = stats::zero(ctx.unit.size());", "    std::vector<ItemStats> parts;"]
    L += [f'    if (live(own, "{n}")) parts.push_back({ns(n)}::stats(s.{n}, own, ctx));' for n, _ in hooks(items, "stats")]
    L += ["    std::vector<const ItemStats*> ps{&z};", "    for (auto& p : parts) ps.push_back(&p);",
          "    return stats::combine(ps);", "}", ""]
    L += ["HolderDefense holder_defense(const ItemEffectState& s, const Owned& own, const Ctx& ctx) {",
          "    std::vector<HolderDefense> parts;"]
    L += [f'    if (live(own, "{n}")) parts.push_back({ns(n)}::defense(s.{n}, own, ctx));' for n, _ in hooks(items, "defense")]
    L += ["    std::vector<const HolderDefense*> ps;", "    for (auto& p : parts) ps.push_back(&p);",
          "    return combine_defense(ps, (int)ctx.unit.size());", "}", ""]
    L += ["StatusFlags status(const ItemEffectState& s, const Owned& own, const Ctx& ctx) {",
          "    StatusFlags out;", "    out.ghosted.assign(ctx.unit.size(), 0);"]
    for n, _ in hooks(items, "status"):
        L += [f'    if (live(own, "{n}")) {{', f"        StatusFlags f = {ns(n)}::status(s.{n}, own, ctx);",
              "        for (size_t h = 0; h < out.ghosted.size(); ++h) out.ghosted[h] = out.ghosted[h] | f.ghosted[h];",
              "    }"]
    L += ["    return out;", "}", ""]
    L += ["Debuffs target_debuffs(const ItemEffectState& s, const Owned& own, const Ctx& ctx, const Units& u) {",
          "    std::vector<Debuffs> parts;"]
    L += [f'    if (live(own, "{n}")) parts.push_back({ns(n)}::debuffs(s.{n}, own, ctx, u));' for n, _ in hooks(items, "debuffs")]
    L += ["    std::vector<const Debuffs*> ps;", "    for (auto& p : parts) ps.push_back(&p);",
          "    return combine_debuffs(ps, (int)u.x.size());", "}", ""]
    # packet_amp = per-target dealt_amp of the source holder + tag-filtered packet_amp
    L += ["Arr<float> packet_amp(const ItemEffectState& s, const Owned& own, const Ctx& ctx, const Units& u,",
          "                      const Packets& p) {",
          "    const size_t c = ctx.unit.size(), n = u.x.size(), P = size(p);",
          "    Arr<float> amp(c * n, 0.f);"]
    for n, _ in hooks(items, "dealt_amp"):
        L += [f'    if (live(own, "{n}")) {{', f"        Arr<float> a = {ns(n)}::dealt_amp(s.{n}, own, ctx, u);",
              "        for (size_t k = 0; k < c * n; ++k) amp[k] = amp[k] + a[k];", "    }"]
    L += ["    Arr<float> out(P, 0.f);", "    for (size_t i = 0; i < P; ++i) {", "        float sum = 0.f;",
          "        int dst = clampi(p.dst[i], 0, (int)n - 1);",
          "        for (size_t h = 0; h < c; ++h) sum = sum + (p.src[i] == ctx.unit[h] ? amp[h * n + dst] : 0.f);",
          "        out[i] = sum;", "    }"]
    for n, _ in hooks(items, "packet_amp"):
        L += [f'    if (live(own, "{n}")) {{', f"        Arr<float> a = {ns(n)}::packet_amp(s.{n}, own, ctx, u, p);",
              "        for (size_t i = 0; i < P; ++i) out[i] = out[i] + a[i];", "    }"]
    L += ["    return out;", "}", ""]
    L += ["AttackMods attack_mods(const ItemEffectState& s, const Owned& own, const Ctx& ctx, const Units& u,",
          "                       const Arr<int32_t>& target) {",
          "    AttackMods out;", "    out.force_crit.assign(ctx.unit.size(), 0), out.crit_scale.assign(ctx.unit.size(), 1.f);"]
    for n, _ in hooks(items, "attack_mods"):
        L += [f'    if (live(own, "{n}")) {{', f"        AttackMods r = {ns(n)}::attack_mods(s.{n}, own, ctx, u, target);",
              "        for (size_t h = 0; h < out.force_crit.size(); ++h) {",
              "            if (r.force_crit[h]) out.crit_scale[h] = r.crit_scale[h];",
              "            out.force_crit[h] = out.force_crit[h] | r.force_crit[h];", "        }", "    }"]
    L += ["    return out;", "}", ""]
    for hook, (param, arg) in EVENT.items():
        sig = f", {param}" if param else ""
        call = f", {arg}" if arg else ""
        L += [f"Effects {hook}(ItemEffectState& s, const Owned& own, const Ctx& ctx, const Units& u{sig}) {{",
              "    Effects out = no_effects((int)ctx.unit.size(), (int)u.x.size());"]
        for n, _ in hooks(items, hook):
            L += [f'    if (live(own, "{n}")) {{', f"        auto [st, eff] = {ns(n)}::{hook}(s.{n}, own, ctx, u{call});",
                  f"        s.{n} = st;", "        merge_into(out, eff);", "    }"]
        L += ["    return out;", "}", ""]
    L += ["Effects active(ItemEffectState& s, const Owned& own, const Ctx& ctx, const Units& u, const Arr<int32_t>& request,",
          "               ActiveOut& out) {",
          "    size_t c = ctx.unit.size();",
          "    out.used.assign(c, 0), out.cast_time.assign(c, 0.f), out.can_move.assign(c, 1), out.attack_reset.assign(c, 0);",
          "    Effects eff_all = no_effects((int)c, (int)u.x.size());"]
    for n, _ in hooks(items, "active"):
        L += [f'    if (live(own, "{n}")) {{', f"        auto [st, eff, r] = {ns(n)}::active(s.{n}, own, ctx, u, request);",
              f"        s.{n} = st;", "        merge_into(eff_all, eff);",
              "        for (size_t h = 0; h < c; ++h) {",
              "            if (r.used[h]) out.cast_time[h] = r.cast_time[h], out.can_move[h] = r.can_move[h];",
              "            out.used[h] = out.used[h] | r.used[h], out.attack_reset[h] = out.attack_reset[h] | r.attack_reset[h];",
              "        }", "    }"]
    L += ["    return eff_all;", "}", ""]
    L += ["void on_shop(ItemEffectState& s, const Owned& own, const Ctx& ctx) {"]
    L += [f'    if (live(own, "{n}")) s.{n} = {ns(n)}::on_shop(s.{n}, own, ctx);' for n, _ in hooks(items, "on_shop")]
    L += ["}", ""]
    L += ["}  // namespace lanesim::champ::items", "", "namespace lanesim::champ::runes {", ""]
    rn = lambda n: f"::lanesim::runes::{n}"                                       # noqa: E731
    P = "const Arr<int32_t>& page"
    L += [f"ItemStats stats(const RuneEffectState& s, {P}, const Ctx& ctx, const RuneEvents& ev) {{",
          "    ItemStats z = stats::zero(ctx.unit.size());", "    std::vector<ItemStats> parts;"]
    L += [f"    parts.push_back({rn(n)}::stats(s.{n}, page, ctx, ev));" for n, _ in hooks(runes, "stats")]
    L += ["    std::vector<const ItemStats*> ps{&z};", "    for (auto& p : parts) ps.push_back(&p);",
          "    return ::lanesim::stats::combine(ps);", "}", ""]
    L += [f"Debuffs debuffs(const RuneEffectState& s, {P}, const Ctx& ctx, const Units& u, const RuneEvents& ev) {{",
          "    std::vector<Debuffs> parts;"]
    L += [f"    parts.push_back({rn(n)}::debuffs(s.{n}, page, ctx, u, ev));" for n, _ in hooks(runes, "debuffs")]
    L += ["    std::vector<const Debuffs*> ps;", "    for (auto& p : parts) ps.push_back(&p);",
          "    return combine_debuffs(ps, (int)u.x.size());", "}", ""]
    for hook in ("packet_amp", "packet_block"):
        L += [f"Arr<float> {hook}(const RuneEffectState& s, {P}, const Ctx& ctx, const Units& u, const RuneEvents& ev,",
              "                    const Packets& p) {", "    Arr<float> out(size(p), 0.f);"]
        for n, _ in hooks(runes, hook):
            L += ["    {", f"        Arr<float> a = {rn(n)}::{hook}(s.{n}, page, ctx, u, ev, p);",
                  "        for (size_t i = 0; i < out.size(); ++i) out[i] = out[i] + a[i];", "    }"]
        L += ["    return out;", "}", ""]
    L += [f"Arr<float> heal_mult(const RuneEffectState& s, {P}, const Ctx& ctx, const RuneEvents& ev) {{",
          "    Arr<float> out(ctx.unit.size(), 1.f);"]
    for n, _ in hooks(runes, "heal_mult"):
        L += ["    {", f"        Arr<float> a = {rn(n)}::heal_mult(s.{n}, page, ctx, ev);",
              "        for (size_t h = 0; h < out.size(); ++h) out[h] = out[h] * a[h];", "    }"]
    L += ["    return out;", "}", ""]
    for hook in ("on_cast", "on_attack", "on_hit", "on_cc", "periodic", "on_damage", "on_takedown"):
        L += [f"Effects {hook}(RuneEffectState& s, {P}, const Ctx& ctx, const Units& u, const RuneEvents& ev) {{",
              "    Effects out = no_effects((int)ctx.unit.size(), (int)u.x.size());"]
        for n, _ in hooks(runes, hook):
            L += ["    {", f"        auto [st, eff] = {rn(n)}::{hook}(s.{n}, page, ctx, u, ev);", f"        s.{n} = st;",
                  "        merge_into(out, eff);", "    }"]
        L += ["    return out;", "}", ""]
    L += [f"void post_tick(RuneEffectState& s, {P}, const Ctx& ctx, const Units& u, const RuneEvents& ev) {{"]
    L += [f"    s.{n} = {rn(n)}::post_tick(s.{n}, page, ctx, u, ev);" for n, _ in hooks(runes, "post_tick")]
    L += ["}", ""]
    L += [f"RuneOutputs outputs(const RuneEffectState& s, {P}, const Ctx& ctx, const RuneEvents& ev) {{",
          "    RuneOutputs out = no_outputs((int)ctx.unit.size(), n_items());"]
    L += [f"    merge_outputs_into(out, {rn(n)}::outputs(s.{n}, page, ctx, ev));" for n, _ in hooks(runes, "outputs")]
    L += ["    return out;", "}", "", "}  // namespace lanesim::champ::runes", ""]
    # The module helpers combat_tick reads directly stay hand-written (dispatch_helpers.cpp).
    OUT.write_text("\n".join(L))
    print("wrote", OUT)


if __name__ == "__main__":
    main()
