"""Generate native/src/champ/dispatch.cpp: the item and rune hook dispatch over the ported modules, in the JAX
``MODULES`` order with the same merge rules (items/effects/__init__.py, runes/effects/__init__.py).

Item modules run only if some holder can hold one of their items (COVERAGE + ACTIVE_ITEMS, ``_each``); rune
modules always run. Module hooks are ``lanesim::items::<module>::<hook>`` / ``lanesim::runes::<module>::<hook>``
with the JAX signatures (state by value, ``std::tuple`` results).

    python -m ops.native.gen_dispatch
"""
from __future__ import annotations

import os
import re
from pathlib import Path

OUT = Path(__file__).resolve().parents[2] / "native" / "src" / "champ" / "dispatch.cpp"
EVENT = {"on_attack": ("const Attack& a", "a"), "on_hit": ("const Attack& a", "a"), "on_cast": ("const Cast& cast", "cast"),
         "on_cc": ("const CC& cc", "cc"), "on_damage": ("const Report& r", "r"), "periodic": ("", ""),
         "on_takedown": ("const Kills& k", "k")}


CALL = re.compile(r"::lanesim::(items|runes)::(\w+)::(\w+)\(")
FUNC = re.compile(r"^[A-Za-z].* (\w+)\(")


def profiled(lines: list[str]) -> list[str]:
    """LS_PROF scopes (native/src/prof.hpp): each dispatch function as ``<area>.<function>``, each module call as
    ``<area>.<module>.<hook>``."""
    out, area, fn = [], "", None
    for line in lines:
        if line.startswith("namespace lanesim::champ::"):
            area = line.split("::")[-1].split()[0]
        m = FUNC.match(line)
        if m and not line.startswith(("namespace", "}")):
            fn = m.group(1)
        call = CALL.search(line)
        if call:
            name = f'LS_PROF("{call.group(1)}.{call.group(2)}.{call.group(3)}");'
            ind = line[:len(line) - len(line.lstrip())]
            body = line.strip()
            live = re.match(r'(if \((?:live|run)\([^()]*\)\)) (.*;)$', body)
            if live:
                line = f"{ind}{live.group(1)} {{ {name} {live.group(2)} }}"
            elif re.match(r"(parts\.push_back|s\.\w+ =|merge_outputs_into)\(?", body) and body.endswith(";"):
                line = f"{ind}{{ {name} {body} }}"
            else:
                out.append(ind + name)
        out.append(line)
        if fn and line.endswith(") {") and fn not in ("module_rows", "live", "check_unported"):
            out.append(f'    LS_PROF("{area}.{fn}");')
            fn = None
        elif fn and line.endswith("{") and not line.startswith(" ") and "(" not in line:
            fn = None
    return out


def main() -> None:
    os.environ.setdefault("JAX_PLATFORMS", "cpu")
    from lanerl_jax.modern.items import effects as IE
    from lanerl_jax.modern.runes import effects as RE
    hdrs = "".join(p.read_text() for p in (OUT.parent / "items").glob("*.hpp"))
    all_items = [(m.__name__.rsplit(".", 1)[-1], m) for m in IE.MODULES]
    # Modules without a native port (no Garen/Jax item): the dispatch refuses a world where they could run.
    unported = [n for n, _ in all_items if f"namespace {n} {{" not in hdrs]
    items = [(n, m) for n, m in all_items if n not in unported]
    runes = [(m.__name__.rsplit(".", 1)[-1], m) for m in RE.MODULES]
    L = ["// GENERATED by ops/native/gen_dispatch.py: item and rune dispatch over the ported modules.",
         '#include "dispatch.hpp"', "", '#include "../prof.hpp"', '#include "items/items.hpp"', '#include "marshal.hpp"', '#include "items/items_b.hpp"',
         '#include "runes/runes.hpp"', '#include "stats.hpp"', "", "#include <cstdint>", "#include <stdexcept>", "#include <unordered_map>", "#include <utility>", "", "namespace lanesim::champ::items {", "",
         "namespace {",
         "// The module's catalog rows (consts dispatch.items.<module>), per call-site name literal.",
         "const std::vector<int>& module_rows(const char* name) {",
         "    static thread_local std::unordered_map<const char*, std::vector<int>> cache;",
         "    auto it = cache.find(name);",
         "    if (it != cache.end()) return it->second;",
         "    std::vector<int> rows;",
         "    for (float id : data::table(std::string(\"dispatch.items.\") + name))",
         "        if (id != 0.f) rows.push_back(item_row((int)id));",
         "    return cache.emplace(name, std::move(rows)).first->second;",
         "}",
         "// items.effects._each: some holder can hold one of the module's items.",
         "bool live(const Owned& own, const char* name) {",
         "    const std::vector<int>& rows = module_rows(name);",
         "    if (own.allowed.size() == 0) return true;",
         "    int ni = n_items();",
         "    size_t c = own.allowed.size() / ni;",
         "    for (int r : rows)",
         "        for (size_t h = 0; h < c; ++h)",
         "            if (own.allowed[h * ni + r]) return true;",
         "    return false;",
         "}",
         "// Item modules with no native port: only worlds where no holder can hold their items are supported.",
         "void check_unported(const Owned& own) {",
         *[f'    if (live(own, "{n}")) throw std::runtime_error("item module {n} is not ported (allow-list needed)");'
           for n in unported],
         "}",
         "",
         "// Dormant modules: no holder owns one of the module's items and its state is still the world's initial",
         "// state, so every hook is an identity with neutral outputs and is skipped. The state comparison is cached",
         "// for the tick (a skipped module cannot change); a module that runs is not dormant for the rest of the tick.",
         "enum : uint8_t { UNKNOWN, INITIAL, MOVED };",
         f"constexpr int N_MODULES = {len(items)};",
         "struct Dormancy {",
         "    const ItemEffectState* initial = nullptr;",
         "    uint8_t mark[N_MODULES] = {};",
         "};",
         "thread_local Dormancy dormancy;",
         "bool owned_now(const Owned& own, const char* name) {",
         "    int ni = n_items();",
         "    size_t c = own.counts.size() / ni;",
         "    for (int r : module_rows(name))",
         "        for (size_t h = 0; h < c; ++h)",
         "            if (own.counts[h * ni + r] > 0) return true;",
         "    return false;",
         "}",
         "template <class S>",
         "bool run(const Owned& own, const char* name, int k, const S& s, S ItemEffectState::*field) {",
         "    if (!live(own, name)) return false;",
         "    Dormancy& d = dormancy;",
         "    if (!d.initial) return true;",
         "    if (owned_now(own, name)) {",
         "        d.mark[k] = MOVED;",
         "        return true;",
         "    }",
         "    if (d.mark[k] == UNKNOWN) d.mark[k] = marshal::same_bits(s, d.initial->*field) ? INITIAL : MOVED;",
         "    return d.mark[k] == MOVED;",
         "}",
         "}  // namespace",
         "",
         "void set_dormancy(const ItemEffectState* initial) { dormancy = Dormancy{initial, {}}; }",
         ""]
    index = {n: k for k, (n, _) in enumerate(items)}

    def gated(lines: list[str]) -> list[str]:
        """``live(own, "<module>")`` in the hook dispatch becomes the dormancy-aware ``run``."""
        def sub(m):
            n = m.group(1)
            return f'run(own, "{n}", {index[n]}, s.{n}, &ItemEffectState::{n})'
        return [ln if "throw std::runtime_error" in ln or "bool live(" in ln
                else re.sub(r'live\(own, "(\w+)"\)', sub, ln) for ln in lines]
    hooks = lambda mods, h: [(n, m) for n, m in mods if hasattr(m, h)]           # noqa: E731
    ns = lambda n: f"::lanesim::items::{n}"                                       # noqa: E731

    # stats / defense / status / debuffs
    L += ["ItemStats dynamic_stats(const ItemEffectState& s, const Owned& own, const Ctx& ctx) {",
          "    check_unported(own);",
          "    ItemStats z = stats::zero(ctx.unit.size());", "    std::vector<ItemStats> parts;"]
    L += [f'    if (live(own, "{n}")) parts.push_back({ns(n)}::stats(s.{n}, own, ctx));' for n, _ in hooks(items, "stats")]
    L += ["    std::vector<const ItemStats*> ps{&z};", "    for (auto& p : parts) ps.push_back(&p);",
          "    return stats::combine(ps);", "}", ""]
    L += ["HolderDefense holder_defense(const ItemEffectState& s, const Owned& own, const Ctx& ctx) {",
          "    std::vector<HolderDefense> parts;"]
    L += [f'    if (live(own, "{n}")) parts.push_back({ns(n)}::defense(s.{n}, own, ctx));' for n, _ in hooks(items, "defense")]
    L += ["    std::vector<const HolderDefense*> ps;", "    for (auto& p : parts) ps.push_back(&p);",
          "    return combine_defense(ps, (int)ctx.unit.size());", "}", ""]
    L += ["StatusFlags status(const ItemEffectState& s, const Owned& own, const Ctx& ctx) {",
          "    StatusFlags out;", "    out.ghosted.assign(ctx.unit.size(), 0);"]
    for n, _ in hooks(items, "status"):
        L += [f'    if (live(own, "{n}")) {{', f"        StatusFlags f = {ns(n)}::status(s.{n}, own, ctx);",
              "        for (size_t h = 0; h < out.ghosted.size(); ++h) out.ghosted[h] = out.ghosted[h] | f.ghosted[h];",
              "    }"]
    L += ["    return out;", "}", ""]
    L += ["Debuffs target_debuffs(const ItemEffectState& s, const Owned& own, const Ctx& ctx, const Units& u) {",
          "    std::vector<Debuffs> parts;"]
    L += [f'    if (live(own, "{n}")) parts.push_back({ns(n)}::debuffs(s.{n}, own, ctx, u));' for n, _ in hooks(items, "debuffs")]
    L += ["    std::vector<const Debuffs*> ps;", "    for (auto& p : parts) ps.push_back(&p);",
          "    return combine_debuffs(ps, (int)u.x.size());", "}", ""]
    # packet_amp = per-target dealt_amp of the source holder + tag-filtered packet_amp
    L += ["Arr<float> packet_amp(const ItemEffectState& s, const Owned& own, const Ctx& ctx, const Units& u,",
          "                      const Packets& p) {",
          "    const size_t c = ctx.unit.size(), n = u.x.size(), P = size(p);",
          "    Arr<float> amp(c * n, 0.f);"]
    for n, _ in hooks(items, "dealt_amp"):
        L += [f'    if (live(own, "{n}")) {{', f"        Arr<float> a = {ns(n)}::dealt_amp(s.{n}, own, ctx, u);",
              "        for (size_t k = 0; k < c * n; ++k) amp[k] = amp[k] + a[k];", "    }"]
    L += ["    Arr<float> out(P, 0.f);", "    for (size_t i = 0; i < P; ++i) {", "        float sum = 0.f;",
          "        int dst = clampi(p.dst[i], 0, (int)n - 1);",
          "        for (size_t h = 0; h < c; ++h) sum = sum + (p.src[i] == ctx.unit[h] ? amp[h * n + dst] : 0.f);",
          "        out[i] = sum;", "    }"]
    for n, _ in hooks(items, "packet_amp"):
        L += [f'    if (live(own, "{n}")) {{', f"        Arr<float> a = {ns(n)}::packet_amp(s.{n}, own, ctx, u, p);",
              "        for (size_t i = 0; i < P; ++i) out[i] = out[i] + a[i];", "    }"]
    L += ["    return out;", "}", ""]
    L += ["AttackMods attack_mods(const ItemEffectState& s, const Owned& own, const Ctx& ctx, const Units& u,",
          "                       const Arr<int32_t>& target) {",
          "    AttackMods out;", "    out.force_crit.assign(ctx.unit.size(), 0), out.crit_scale.assign(ctx.unit.size(), 1.f);"]
    for n, _ in hooks(items, "attack_mods"):
        L += [f'    if (live(own, "{n}")) {{', f"        AttackMods r = {ns(n)}::attack_mods(s.{n}, own, ctx, u, target);",
              "        for (size_t h = 0; h < out.force_crit.size(); ++h) {",
              "            if (r.force_crit[h]) out.crit_scale[h] = r.crit_scale[h];",
              "            out.force_crit[h] = out.force_crit[h] | r.force_crit[h];", "        }", "    }"]
    L += ["    return out;", "}", ""]
    for hook, (param, arg) in EVENT.items():
        sig = f", {param}" if param else ""
        call = f", {arg}" if arg else ""
        L += [f"Effects {hook}(ItemEffectState& s, const Owned& own, const Ctx& ctx, const Units& u{sig}) {{",
              "    Effects out = no_effects((int)ctx.unit.size(), (int)u.x.size());"]
        for n, _ in hooks(items, hook):
            L += [f'    if (live(own, "{n}")) {{', f"        auto [st, eff] = {ns(n)}::{hook}(std::move(s.{n}), own, ctx, u{call});",
                  f"        s.{n} = std::move(st);", "        merge_into(out, eff);", "    }"]
        L += ["    return out;", "}", ""]
    L += ["Effects active(ItemEffectState& s, const Owned& own, const Ctx& ctx, const Units& u, const Arr<int32_t>& request,",
          "               ActiveOut& out) {",
          "    size_t c = ctx.unit.size();",
          "    out.used.assign(c, 0), out.cast_time.assign(c, 0.f), out.can_move.assign(c, 1), out.attack_reset.assign(c, 0);",
          "    Effects eff_all = no_effects((int)c, (int)u.x.size());"]
    for n, _ in hooks(items, "active"):
        L += [f'    if (live(own, "{n}")) {{', f"        auto [st, eff, r] = {ns(n)}::active(std::move(s.{n}), own, ctx, u, request);",
              f"        s.{n} = std::move(st);", "        merge_into(eff_all, eff);",
              "        for (size_t h = 0; h < c; ++h) {",
              "            if (r.used[h]) out.cast_time[h] = r.cast_time[h], out.can_move[h] = r.can_move[h];",
              "            out.used[h] = out.used[h] | r.used[h], out.attack_reset[h] = out.attack_reset[h] | r.attack_reset[h];",
              "        }", "    }"]
    L += ["    return eff_all;", "}", ""]
    L += ["void on_shop(ItemEffectState& s, const Owned& own, const Ctx& ctx) {"]
    L += [f'    if (live(own, "{n}")) s.{n} = {ns(n)}::on_shop(std::move(s.{n}), own, ctx);' for n, _ in hooks(items, "on_shop")]
    L += ["}", ""]
    L += ["}  // namespace lanesim::champ::items", "", "namespace lanesim::champ::runes {", ""]
    rn = lambda n: f"::lanesim::runes::{n}"                                       # noqa: E731
    P = "const Arr<int32_t>& page"
    ridx = {n: k for k, (n, _) in enumerate(runes)}
    G = lambda n: f'run(page, "{n}", {ridx[n]}, s.{n}, &RuneEffectState::{n})'   # noqa: E731
    L += ["namespace {",
          "// Dormant trees, as for items: none of the tree's runes on a page and the state still the initial one.",
          "enum : uint8_t { UNKNOWN, INITIAL, MOVED };",
          f"constexpr int N_MODULES = {len(runes)};",
          "struct Dormancy {",
          "    const RuneEffectState* initial = nullptr;",
          "    uint8_t mark[N_MODULES] = {};",
          "};",
          "thread_local Dormancy dormancy;",
          "// The tree's rune rows (consts dispatch.runes.<module>), per call-site name literal.",
          "const std::vector<int>& module_rows(const char* name) {",
          "    static thread_local std::unordered_map<const char*, std::vector<int>> cache;",
          "    auto it = cache.find(name);",
          "    if (it != cache.end()) return it->second;",
          "    std::vector<int> rows;",
          "    for (float id : data::table(std::string(\"dispatch.runes.\") + name))",
          "        if (id != 0.f) rows.push_back(rune_row((int)id));",
          "    return cache.emplace(name, std::move(rows)).first->second;",
          "}",
          "template <class S>",
          "bool run(const Arr<int32_t>& page, const char* name, int k, const S& s, S RuneEffectState::*field) {",
          "    Dormancy& d = dormancy;",
          "    if (!d.initial) return true;",
          "    static const size_t nr = data::table(\"runes.ids\").size();     // page: (C, runes)",
          "    size_t c = page.size() / nr;",
          "    for (int r : module_rows(name))",
          "        for (size_t h = 0; h < c; ++h)",
          "            if (page[h * nr + r] > 0) return true;",
          "    if (d.mark[k] == UNKNOWN) d.mark[k] = marshal::same_bits(s, d.initial->*field) ? INITIAL : MOVED;",
          "    return d.mark[k] == MOVED;",
          "}",
          "}  // namespace",
          "",
          "void set_dormancy(const RuneEffectState* initial) { dormancy = Dormancy{initial, {}}; }",
          ""]
    L += [f"ItemStats stats(const RuneEffectState& s, {P}, const Ctx& ctx, const RuneEvents& ev) {{",
          "    ItemStats z = stats::zero(ctx.unit.size());", "    std::vector<ItemStats> parts;"]
    L += [f"    if ({G(n)}) parts.push_back({rn(n)}::stats(s.{n}, page, ctx, ev));" for n, _ in hooks(runes, "stats")]
    L += ["    std::vector<const ItemStats*> ps{&z};", "    for (auto& p : parts) ps.push_back(&p);",
          "    return ::lanesim::stats::combine(ps);", "}", ""]
    L += [f"Debuffs debuffs(const RuneEffectState& s, {P}, const Ctx& ctx, const Units& u, const RuneEvents& ev) {{",
          "    std::vector<Debuffs> parts;"]
    L += [f"    if ({G(n)}) parts.push_back({rn(n)}::debuffs(s.{n}, page, ctx, u, ev));" for n, _ in hooks(runes, "debuffs")]
    L += ["    std::vector<const Debuffs*> ps;", "    for (auto& p : parts) ps.push_back(&p);",
          "    return combine_debuffs(ps, (int)u.x.size());", "}", ""]
    for hook in ("packet_amp", "packet_block"):
        L += [f"Arr<float> {hook}(const RuneEffectState& s, {P}, const Ctx& ctx, const Units& u, const RuneEvents& ev,",
              "                    const Packets& p) {", "    Arr<float> out(size(p), 0.f);"]
        for n, _ in hooks(runes, hook):
            L += [f"    if ({G(n)}) {{", f"        Arr<float> a = {rn(n)}::{hook}(s.{n}, page, ctx, u, ev, p);",
                  "        for (size_t i = 0; i < out.size(); ++i) out[i] = out[i] + a[i];", "    }"]
        L += ["    return out;", "}", ""]
    L += [f"Arr<float> heal_mult(const RuneEffectState& s, {P}, const Ctx& ctx, const RuneEvents& ev) {{",
          "    Arr<float> out(ctx.unit.size(), 1.f);"]
    for n, _ in hooks(runes, "heal_mult"):
        L += [f"    if ({G(n)}) {{", f"        Arr<float> a = {rn(n)}::heal_mult(s.{n}, page, ctx, ev);",
              "        for (size_t h = 0; h < out.size(); ++h) out[h] = out[h] * a[h];", "    }"]
    L += ["    return out;", "}", ""]
    for hook in ("on_cast", "on_attack", "on_hit", "on_cc", "periodic", "on_damage", "on_takedown"):
        L += [f"Effects {hook}(RuneEffectState& s, {P}, const Ctx& ctx, const Units& u, const RuneEvents& ev) {{",
              "    Effects out = no_effects((int)ctx.unit.size(), (int)u.x.size());"]
        for n, _ in hooks(runes, hook):
            L += [f"    if ({G(n)}) {{", f"        auto [st, eff] = {rn(n)}::{hook}(std::move(s.{n}), page, ctx, u, ev);",
                  f"        s.{n} = std::move(st);",
                  "        merge_into(out, eff);", "    }"]
        L += ["    return out;", "}", ""]
    L += [f"void post_tick(RuneEffectState& s, {P}, const Ctx& ctx, const Units& u, const RuneEvents& ev) {{"]
    L += [f"    if ({G(n)}) s.{n} = {rn(n)}::post_tick(std::move(s.{n}), page, ctx, u, ev);" for n, _ in hooks(runes, "post_tick")]
    L += ["}", ""]
    L += [f"RuneOutputs outputs(const RuneEffectState& s, {P}, const Ctx& ctx, const RuneEvents& ev) {{",
          "    RuneOutputs out = no_outputs((int)ctx.unit.size(), n_items());"]
    L += [f"    if ({G(n)}) merge_outputs_into(out, {rn(n)}::outputs(s.{n}, page, ctx, ev));" for n, _ in hooks(runes, "outputs")]
    L += ["    return out;", "}", "", "}  // namespace lanesim::champ::runes", "",
          "namespace lanesim::champ {",
          "DormancyScope::DormancyScope(const ItemEffectState* items, const RuneEffectState* runes) {",
          "    items::set_dormancy(items), runes::set_dormancy(runes);",
          "}",
          "DormancyScope::~DormancyScope() { items::set_dormancy(nullptr), runes::set_dormancy(nullptr); }",
          "}  // namespace lanesim::champ", ""]
    # The module helpers combat_tick reads directly stay hand-written (dispatch_helpers.cpp).
    OUT.write_text("\n".join(profiled(gated(L))))
    print("wrote", OUT)


if __name__ == "__main__":
    main()
