"""``TickScratch``: the values the phases of one tick pass to each other (``world/tick.py``)."""
from __future__ import annotations

from typing import Any, NamedTuple


class TickScratch(NamedTuple):
    """The tick's data-flow map. Each comment names the writing phase (later rewrites in brackets)."""
    s0: Any = None              # step: the incoming state (start-of-tick fog; game-over freeze)
    now: Any = None             # step: s.t + dt
    key: Any = None             # step [OBJ]: PRNG key for the next tick
    k_crit: Any = None          # step: crit-roll key (ATTACK)
    champ: Any = None           # INPUT [CASTS, AI, DEATH, TIMERS, FOG]: working ChampionLayer, the next state's
    vis_c: Any = None           # INPUT: (C, N) the champion's team sees the unit (start of tick)
    in_stasis: Any = None       # INPUT: (C,) item stasis
    caps: Any = None            # INPUT: M.capabilities, stasis-gated
    terrain: Any = None         # INPUT: this tick's walkable masks
    attack_order: Any = None    # INPUT [AI: idle acquisition]: (C,) ordered attack target
    moving: Any = None          # INPUT: (C,) walking to move_goal
    goal: Any = None            # INPUT [AI: attack-move]: (C, 2) champion move goal
    amove: Any = None           # INPUT [AI]: AttackMove
    static: Any = None          # STATS: ItemStats without dynamic stats
    st_static: Any = None       # STATS: ChampionStats of ``static``
    so: Any = None              # OBJ: objectives_step output (None without objectives)
    cinfo: Any = None           # OBJ: OBJ.ChampInfo
    st: Any = None              # CASTS: the tick's ChampionStats (with last tick's dynamic stats and slows)
    summ_world: Any = None      # CASTS: ItemStats static + last tick's dynamic stats
    units: Any = None           # CASTS [AI, MOVE, ATTACK]: WorldUnits view
    kctx: Any = None            # CASTS: K.KitCtx
    ictx: Any = None            # CASTS [MOVE]: item Ctx
    locked: Any = None          # CASTS: (C,) cast lockout (no casts, attacks or movement)
    item_casting: Any = None    # CASTS: (C,) movable item-active cast (Stridebreaker)
    cast_order: Any = None      # CASTS: W.CastOrder the kits saw
    kits: Any = None            # CASTS [ATTACK, DAMAGE, DEATH]: kit state
    kit_out: Any = None         # CASTS: kit cast + periodic output
    kmods: Any = None           # CASTS: K.attack_mods
    reach: Any = None           # CASTS: (C,) attack range incl. kit range
    summ: Any = None            # CASTS: summoner state
    s_eff: Any = None           # CASTS: summoner Effects
    s_out: Any = None           # CASTS: summoner world outputs
    sm: Any = None              # CASTS: Smite output (None without jungle)
    jungle: Any = None          # CASTS [AI, ATTACK, DEATH]: working JungleState
    shop_code: Any = None       # CASTS: (C,) buy/sell result code
    bought: Any = None          # CASTS: (C,) item id bought
    sold: Any = None            # CASTS: (C,) item id sold
    towers: Any = None          # AI [ATTACK, DEATH]: working structure state
    lane_ai: Any = None         # AI: lane AI state
    desired: Any = None         # AI: (N,) desired attack target
    lane_goal: Any = None       # AI: (N, 2) lane-minion goals
    lane_stop: Any = None       # AI: (N,) lane minions holding position
    mai: Any = None             # AI: monster AI output (None without jungle)
    mon_goal: Any = None        # AI: (N, 2) monster goals
    mon_speed: Any = None       # AI: (N,) monster move speed
    mon_move: Any = None        # AI: (N,) monster moving
    mbuf: Any = None            # AI: Hand of Baron minion buffs (None without objectives)
    attack_order_eff: Any = None  # AI: (C,) attack target incl. attack-move
    t_ok_eff: Any = None        # AI: (C,) has a live attack target
    moving_eff: Any = None      # AI: (C,) walks to ``goal``
    tp_lock: Any = None         # MOVE: (C,) Teleport channel/dash
    sres: Any = None            # MOVE: (N,) slow resist
    ms: Any = None              # MOVE: (N,) move speed
    dstart: Any = None          # MOVE: (C,) dash started
    in_dash: Any = None         # MOVE: (C,) dashing
    att: Any = None             # ATTACK: AttackState
    launched: Any = None        # ATTACK: (N,) attacks launched
    started: Any = None         # ATTACK: (N,) windups started
    cancelled: Any = None       # ATTACK: (N,) windups cancelled
    reset: Any = None           # ATTACK: (N,) attack resets
    attack: Any = None          # ATTACK: champion Attack (missile arrivals count as hits)
    missiles: Any = None        # ATTACK: Missiles
    m_over: Any = None          # ATTACK: missile overflow
    direct: Any = None          # ATTACK: melee attack packets
    arrived: Any = None         # ATTACK: missile arrival packets
    og_pk: Any = None           # ATTACK: Overgrowth packets
    extra_atk: Any = None       # ATTACK: list of extra monster attack packets
    obj_cc: Any = None          # ATTACK: objective attack CC (None without objectives)
    ward_hits: Any = None       # ATTACK: (2W,) champion hits per ward slot
    ward_hitter: Any = None     # ATTACK: (2W,) hitting unit per ward slot
    kit_all: Any = None         # ATTACK: kit output incl. on_attack/on_hit
    jfx: Any = None             # ATTACK: jungle combat effects (None without jungle)
    out: Any = None             # DAMAGE: combat_tick output
    kdef: Any = None            # DAMAGE: K.defense
    k_dmg: Any = None           # DAMAGE: K.on_damage output
    cc_now: Any = None          # DAMAGE: kit CC
    cc_items: Any = None        # DAMAGE: item CC flags
    hp: Any = None              # DAMAGE [CC, DEATH, TIMERS]: (N,) working HP
    max_hp: Any = None          # DAMAGE [TIMERS]: (N,) working max HP
    shields: Any = None         # DAMAGE [CC]: D.Shields
    status: Any = None          # DAMAGE [CC]: UnitStatus
    extra: Any = None           # CC: merged heal/mana effects
    item_cleanse: Any = None    # CC: item-active world effects (cleanse, cd rate, mana cost, transform, dash)
    cc: Any = None              # CC: CCTimers (deaths cleared in commit)
    died: Any = None            # DEATH: (N,) died this tick
    minion_died: Any = None     # DEATH: (N,)
    dmg: Any = None             # DEATH: (N, N) damage matrix (next tick)
    death_seen: Any = None      # DEATH: (C, N) own sight of units that died (next tick)
    plates: Any = None          # DEATH: PlateEvents
    took_health: Any = None     # DEATH: (N,) took health damage
    in_f: Any = None            # DEATH: (C,) in own fountain
    epic: Any = None            # DEATH: (C,) epic takedowns (next tick)
    large: Any = None           # DEATH: (C,) large-monster kills (next tick)
    jrw: Any = None             # DEATH: jungle rewards (None without jungle)
    eco: Any = None             # DEATH: EconomyOut
    econ: Any = None            # DEATH [TIMERS]: next economy state
    alive: Any = None           # TIMERS: (N,) next-state unit columns from here to targetable
    x: Any = None
    y: Any = None
    kind: Any = None
    sub: Any = None
    team: Any = None
    spawn_seq: Any = None
    radius: Any = None
    targetable: Any = None
    wards: Any = None           # TIMERS: Wards
    kills: Any = None           # TIMERS: Kills credited (next tick)
    cast_now: Any = None        # TIMERS: (C, 4) slot cast this tick
    reveal: Any = None          # FOG: attack-reveal circles
    visible: Any = None         # FOG: (2, N) next tick's visibility
    sight: Any = None           # FOG: (C, N) next tick's own sight
    ray_over: Any = None        # FOG: sight-ray overflow
