"""A frozen opponent's experience must never reach the learner.

In league play red is a SNAPSHOT -- a frozen past checkpoint, or a scripted
bot. Its transitions are generated by different parameters from the ones
being optimised, and training on them is off-policy data masquerading as
on-policy: the PPO ratio would be measured against log-probs the learner
never produced, and the gradient would pull the live policy toward whatever
the frozen one happened to do.

The guarantee is structural -- ``collect_rollout`` builds its buffer from
``driver.slots[policy_key]``, and a frozen opponent lives under a different
key, so its slots are simply not there. Structural guarantees are the good
kind, but this one is worth pinning: it rests on the key lookup, and a
plausible-looking change (train on "all slots", or reuse one key for both
sides) would silently start training on the opponent. Nothing downstream
would error, and the symptom would be a policy that mysteriously fails to
improve -- which this project has spent a long time chasing for other
reasons.

Two assertions, because either alone is weak:

* the rollout has exactly as many rows as the LEARNER has slots, so the
  opponent contributed none;
* the frozen opponent's parameters are bit-identical after an update, so
  nothing reached it through a shared reference either.
"""
from __future__ import annotations

import copy

import torch

from lanerl_rl.model import LanePolicy, ModelConfig
from lanerl_rl.ppo import DualClipPPO, PPOConfig
from lanerl_train.lane_wiring import LanePolicyActor, collect_rollout, make_lane_adapters
from lanerl_train.tests.fakes import FakeInstance
from lanerl_train.tests.test_episode_boundary import build_env_with
from lanerl_train.vec import EpisodeSpec, SideAssignment, VecDriver

LEARNER = "self"
FROZEN = "opponent"


def _small() -> LanePolicy:
    return LanePolicy(ModelConfig(core_dim=32, d_model=32, ffn_dim=32,
                                  n_layers=1, n_heads=2, mlp_hidden=32))


def _driver_with_frozen_opponent(n_inst: int = 2):
    insts = [FakeInstance(i, step_ms=1000, cs_per_step=1) for i in range(n_inst)]
    env = build_env_with(insts)
    learner = LanePolicyActor(_small())
    frozen = LanePolicyActor(_small())
    adapters = make_lane_adapters(train_step_source=lambda: 0)
    driver = VecDriver(
        env,
        policies={LEARNER: learner, FROZEN: frozen},
        adapter_factory=adapters.adapter_factory,
        encoder=adapters.encoder,
        # blue learns, red is the frozen snapshot -- league shape
        assignments=[SideAssignment(blue=LEARNER, red=FROZEN) for _ in insts],
        episode=EpisodeSpec(max_game_ms=600_000),
    )
    driver.start()
    return driver, learner, frozen, adapters, n_inst


def test_the_rollout_contains_only_the_learners_slots():
    driver, learner, frozen, adapters, n_inst = _driver_with_frozen_opponent()
    rollout = collect_rollout(
        driver, learner, adapters.reward_contexts, LEARNER,
        num_steps=8, gamma=0.99, gae_lambda=0.95,
    )
    buf = rollout.data
    assert buf.B == n_inst, (
        f"the rollout has {buf.B} columns for {n_inst} learner slots. If it "
        f"matches the TOTAL number of driven sides ({2 * n_inst}) then the "
        f"frozen opponent's transitions are being trained on: off-policy "
        f"data with log-probs the learner never produced."
    )
    assert len(driver.slots[LEARNER]) == n_inst
    assert len(driver.slots[FROZEN]) == n_inst, (
        "the frozen opponent is not actually driving anything, so this test "
        "would pass even if opponent data were trained on"
    )
    # every slot in the rollout is a BLUE slot
    assert all(side == "blue" for _, side in driver.slots[LEARNER])


def test_an_update_does_not_touch_the_frozen_opponent():
    driver, learner, frozen, adapters, _ = _driver_with_frozen_opponent()
    before = copy.deepcopy(frozen.policy.state_dict())

    rollout = collect_rollout(
        driver, learner, adapters.reward_contexts, LEARNER,
        num_steps=8, gamma=0.99, gae_lambda=0.95,
    )
    ppo = DualClipPPO(learner.policy, PPOConfig(chunk_len=2, burn_in=1,
                                                minibatch_chunks=2, epochs=1))
    rollout.data.finish(last_value=torch.zeros(rollout.data.B),
                          gamma=0.99, lam=0.95)
    ppo.update(rollout.data)

    after = frozen.policy.state_dict()
    for k, v in before.items():
        assert torch.equal(v, after[k]), (
            f"a training update changed the frozen opponent's {k!r}. The two "
            f"policies are sharing parameters, so 'frozen' is a label rather "
            f"than a fact and the league is playing against itself."
        )

    # ...and the learner DID move, or the test above is satisfied by an
    # update that did nothing at all.
    assert any(p.grad is not None and torch.any(p.grad != 0)
               for p in learner.policy.parameters()), (
        "no learner parameter received a gradient, so 'the opponent did not "
        "change' proves nothing"
    )
