// GENERATED by ops/native/gen_dispatch.py: item and rune dispatch over the ported modules.
#include "dispatch.hpp"

#include "../prof.hpp"
#include "items/items.hpp"
#include "marshal.hpp"
#include "items/items_b.hpp"
#include "runes/runes.hpp"
#include "stats.hpp"

#include <cstdint>
#include <stdexcept>
#include <unordered_map>
#include <utility>

namespace lanesim::champ::items {

namespace {
// The module's catalog rows (consts dispatch.items.<module>), per call-site name literal.
const std::vector<int>& module_rows(const char* name) {
    static thread_local std::unordered_map<const char*, std::vector<int>> cache;
    auto it = cache.find(name);
    if (it != cache.end()) return it->second;
    std::vector<int> rows;
    for (float id : data::table(std::string("dispatch.items.") + name))
        if (id != 0.f) rows.push_back(item_row((int)id));
    return cache.emplace(name, std::move(rows)).first->second;
}
// items.effects._each: some holder can hold one of the module's items.
bool live(const Owned& own, const char* name) {
    const std::vector<int>& rows = module_rows(name);
    if (own.allowed.size() == 0) return true;
    int ni = n_items();
    size_t c = own.allowed.size() / ni;
    for (int r : rows)
        for (size_t h = 0; h < c; ++h)
            if (own.allowed[h * ni + r]) return true;
    return false;
}
// Item modules with no native port: only worlds where no holder can hold their items are supported.
void check_unported(const Owned& own) {
    if (live(own, "support")) throw std::runtime_error("item module support is not ported (allow-list needed)");
    if (live(own, "jungle")) throw std::runtime_error("item module jungle is not ported (allow-list needed)");
}

// Dormant modules: no holder owns one of the module's items and its state is still the world's initial
// state, so every hook is an identity with neutral outputs and is skipped. The state comparison is cached
// for the tick (a skipped module cannot change); a module that runs is not dormant for the rest of the tick.
enum : uint8_t { UNKNOWN, INITIAL, MOVED };
constexpr int N_MODULES = 10;
struct Dormancy {
    const ItemEffectState* initial = nullptr;
    uint8_t mark[N_MODULES] = {};
};
thread_local Dormancy dormancy;
bool owned_now(const Owned& own, const char* name) {
    LS_PROF("items.owned_now");
    int ni = n_items();
    size_t c = own.counts.size() / ni;
    for (int r : module_rows(name))
        for (size_t h = 0; h < c; ++h)
            if (own.counts[h * ni + r] > 0) return true;
    return false;
}
template <class S>
bool run(const Owned& own, const char* name, int k, const S& s, S ItemEffectState::*field) {
    LS_PROF("items.run");
    if (!live(own, name)) return false;
    Dormancy& d = dormancy;
    if (!d.initial) return true;
    if (owned_now(own, name)) {
        d.mark[k] = MOVED;
        return true;
    }
    if (d.mark[k] == UNKNOWN) d.mark[k] = marshal::same_bits(s, d.initial->*field) ? INITIAL : MOVED;
    return d.mark[k] == MOVED;
}
}  // namespace

void set_dormancy(const ItemEffectState* initial) { dormancy = Dormancy{initial, {}}; }

ItemStats dynamic_stats(const ItemEffectState& s, const Owned& own, const Ctx& ctx) {
    LS_PROF("items.dynamic_stats");
    check_unported(own);
    ItemStats z = stats::zero(ctx.unit.size());
    std::vector<ItemStats> parts;
    if (run(own, "consumables", 0, s.consumables, &ItemEffectState::consumables)) { LS_PROF("items.consumables.stats"); parts.push_back(::lanesim::items::consumables::stats(s.consumables, own, ctx)); }
    if (run(own, "starters", 1, s.starters, &ItemEffectState::starters)) { LS_PROF("items.starters.stats"); parts.push_back(::lanesim::items::starters::stats(s.starters, own, ctx)); }
    if (run(own, "spellblade", 2, s.spellblade, &ItemEffectState::spellblade)) { LS_PROF("items.spellblade.stats"); parts.push_back(::lanesim::items::spellblade::stats(s.spellblade, own, ctx)); }
    if (run(own, "hydra", 3, s.hydra, &ItemEffectState::hydra)) { LS_PROF("items.hydra.stats"); parts.push_back(::lanesim::items::hydra::stats(s.hydra, own, ctx)); }
    if (run(own, "fighter", 4, s.fighter, &ItemEffectState::fighter)) { LS_PROF("items.fighter.stats"); parts.push_back(::lanesim::items::fighter::stats(s.fighter, own, ctx)); }
    if (run(own, "defense", 5, s.defense, &ItemEffectState::defense)) { LS_PROF("items.defense.stats"); parts.push_back(::lanesim::items::defense::stats(s.defense, own, ctx)); }
    if (run(own, "mage", 6, s.mage, &ItemEffectState::mage)) { LS_PROF("items.mage.stats"); parts.push_back(::lanesim::items::mage::stats(s.mage, own, ctx)); }
    if (run(own, "marksman", 7, s.marksman, &ItemEffectState::marksman)) { LS_PROF("items.marksman.stats"); parts.push_back(::lanesim::items::marksman::stats(s.marksman, own, ctx)); }
    if (run(own, "boots", 8, s.boots, &ItemEffectState::boots)) { LS_PROF("items.boots.stats"); parts.push_back(::lanesim::items::boots::stats(s.boots, own, ctx)); }
    if (run(own, "actives", 9, s.actives, &ItemEffectState::actives)) { LS_PROF("items.actives.stats"); parts.push_back(::lanesim::items::actives::stats(s.actives, own, ctx)); }
    std::vector<const ItemStats*> ps{&z};
    for (auto& p : parts) ps.push_back(&p);
    return stats::combine(ps);
}

HolderDefense holder_defense(const ItemEffectState& s, const Owned& own, const Ctx& ctx) {
    LS_PROF("items.holder_defense");
    std::vector<HolderDefense> parts;
    if (run(own, "starters", 1, s.starters, &ItemEffectState::starters)) { LS_PROF("items.starters.defense"); parts.push_back(::lanesim::items::starters::defense(s.starters, own, ctx)); }
    if (run(own, "fighter", 4, s.fighter, &ItemEffectState::fighter)) { LS_PROF("items.fighter.defense"); parts.push_back(::lanesim::items::fighter::defense(s.fighter, own, ctx)); }
    if (run(own, "defense", 5, s.defense, &ItemEffectState::defense)) { LS_PROF("items.defense.defense"); parts.push_back(::lanesim::items::defense::defense(s.defense, own, ctx)); }
    if (run(own, "boots", 8, s.boots, &ItemEffectState::boots)) { LS_PROF("items.boots.defense"); parts.push_back(::lanesim::items::boots::defense(s.boots, own, ctx)); }
    std::vector<const HolderDefense*> ps;
    for (auto& p : parts) ps.push_back(&p);
    return combine_defense(ps, (int)ctx.unit.size());
}

StatusFlags status(const ItemEffectState& s, const Owned& own, const Ctx& ctx) {
    LS_PROF("items.status");
    StatusFlags out;
    out.ghosted.assign(ctx.unit.size(), 0);
    if (run(own, "marksman", 7, s.marksman, &ItemEffectState::marksman)) {
        LS_PROF("items.marksman.status");
        StatusFlags f = ::lanesim::items::marksman::status(s.marksman, own, ctx);
        for (size_t h = 0; h < out.ghosted.size(); ++h) out.ghosted[h] = out.ghosted[h] | f.ghosted[h];
    }
    if (run(own, "actives", 9, s.actives, &ItemEffectState::actives)) {
        LS_PROF("items.actives.status");
        StatusFlags f = ::lanesim::items::actives::status(s.actives, own, ctx);
        for (size_t h = 0; h < out.ghosted.size(); ++h) out.ghosted[h] = out.ghosted[h] | f.ghosted[h];
    }
    return out;
}

Debuffs target_debuffs(const ItemEffectState& s, const Owned& own, const Ctx& ctx, const Units& u) {
    LS_PROF("items.target_debuffs");
    std::vector<Debuffs> parts;
    if (run(own, "spellblade", 2, s.spellblade, &ItemEffectState::spellblade)) { LS_PROF("items.spellblade.debuffs"); parts.push_back(::lanesim::items::spellblade::debuffs(s.spellblade, own, ctx, u)); }
    if (run(own, "fighter", 4, s.fighter, &ItemEffectState::fighter)) { LS_PROF("items.fighter.debuffs"); parts.push_back(::lanesim::items::fighter::debuffs(s.fighter, own, ctx, u)); }
    if (run(own, "defense", 5, s.defense, &ItemEffectState::defense)) { LS_PROF("items.defense.debuffs"); parts.push_back(::lanesim::items::defense::debuffs(s.defense, own, ctx, u)); }
    if (run(own, "mage", 6, s.mage, &ItemEffectState::mage)) { LS_PROF("items.mage.debuffs"); parts.push_back(::lanesim::items::mage::debuffs(s.mage, own, ctx, u)); }
    std::vector<const Debuffs*> ps;
    for (auto& p : parts) ps.push_back(&p);
    return combine_debuffs(ps, (int)u.x.size());
}

Arr<float> packet_amp(const ItemEffectState& s, const Owned& own, const Ctx& ctx, const Units& u,
                      const Packets& p) {
    LS_PROF("items.packet_amp");
    const size_t c = ctx.unit.size(), n = u.x.size(), P = size(p);
    Arr<float> amp(c * n, 0.f);
    if (run(own, "mage", 6, s.mage, &ItemEffectState::mage)) {
        LS_PROF("items.mage.dealt_amp");
        Arr<float> a = ::lanesim::items::mage::dealt_amp(s.mage, own, ctx, u);
        for (size_t k = 0; k < c * n; ++k) amp[k] = amp[k] + a[k];
    }
    if (run(own, "marksman", 7, s.marksman, &ItemEffectState::marksman)) {
        LS_PROF("items.marksman.dealt_amp");
        Arr<float> a = ::lanesim::items::marksman::dealt_amp(s.marksman, own, ctx, u);
        for (size_t k = 0; k < c * n; ++k) amp[k] = amp[k] + a[k];
    }
    if (run(own, "boots", 8, s.boots, &ItemEffectState::boots)) {
        LS_PROF("items.boots.dealt_amp");
        Arr<float> a = ::lanesim::items::boots::dealt_amp(s.boots, own, ctx, u);
        for (size_t k = 0; k < c * n; ++k) amp[k] = amp[k] + a[k];
    }
    Arr<float> out(P, 0.f);
    for (size_t i = 0; i < P; ++i) {
        float sum = 0.f;
        int dst = clampi(p.dst[i], 0, (int)n - 1);
        for (size_t h = 0; h < c; ++h) sum = sum + (p.src[i] == ctx.unit[h] ? amp[h * n + dst] : 0.f);
        out[i] = sum;
    }
    if (run(own, "fighter", 4, s.fighter, &ItemEffectState::fighter)) {
        LS_PROF("items.fighter.packet_amp");
        Arr<float> a = ::lanesim::items::fighter::packet_amp(s.fighter, own, ctx, u, p);
        for (size_t i = 0; i < P; ++i) out[i] = out[i] + a[i];
    }
    if (run(own, "marksman", 7, s.marksman, &ItemEffectState::marksman)) {
        LS_PROF("items.marksman.packet_amp");
        Arr<float> a = ::lanesim::items::marksman::packet_amp(s.marksman, own, ctx, u, p);
        for (size_t i = 0; i < P; ++i) out[i] = out[i] + a[i];
    }
    if (run(own, "actives", 9, s.actives, &ItemEffectState::actives)) {
        LS_PROF("items.actives.packet_amp");
        Arr<float> a = ::lanesim::items::actives::packet_amp(s.actives, own, ctx, u, p);
        for (size_t i = 0; i < P; ++i) out[i] = out[i] + a[i];
    }
    return out;
}

AttackMods attack_mods(const ItemEffectState& s, const Owned& own, const Ctx& ctx, const Units& u,
                       const Arr<int32_t>& target) {
    LS_PROF("items.attack_mods");
    AttackMods out;
    out.force_crit.assign(ctx.unit.size(), 0), out.crit_scale.assign(ctx.unit.size(), 1.f);
    if (run(own, "fighter", 4, s.fighter, &ItemEffectState::fighter)) {
        LS_PROF("items.fighter.attack_mods");
        AttackMods r = ::lanesim::items::fighter::attack_mods(s.fighter, own, ctx, u, target);
        for (size_t h = 0; h < out.force_crit.size(); ++h) {
            if (r.force_crit[h]) out.crit_scale[h] = r.crit_scale[h];
            out.force_crit[h] = out.force_crit[h] | r.force_crit[h];
        }
    }
    if (run(own, "marksman", 7, s.marksman, &ItemEffectState::marksman)) {
        LS_PROF("items.marksman.attack_mods");
        AttackMods r = ::lanesim::items::marksman::attack_mods(s.marksman, own, ctx, u, target);
        for (size_t h = 0; h < out.force_crit.size(); ++h) {
            if (r.force_crit[h]) out.crit_scale[h] = r.crit_scale[h];
            out.force_crit[h] = out.force_crit[h] | r.force_crit[h];
        }
    }
    return out;
}

Effects on_attack(ItemEffectState& s, const Owned& own, const Ctx& ctx, const Units& u, const Attack& a) {
    LS_PROF("items.on_attack");
    Effects out = no_effects((int)ctx.unit.size(), (int)u.x.size());
    if (run(own, "marksman", 7, s.marksman, &ItemEffectState::marksman)) {
        LS_PROF("items.marksman.on_attack");
        auto [st, eff] = ::lanesim::items::marksman::on_attack(std::move(s.marksman), own, ctx, u, a);
        s.marksman = std::move(st);
        merge_into(out, eff);
    }
    return out;
}

Effects on_hit(ItemEffectState& s, const Owned& own, const Ctx& ctx, const Units& u, const Attack& a) {
    LS_PROF("items.on_hit");
    Effects out = no_effects((int)ctx.unit.size(), (int)u.x.size());
    if (run(own, "consumables", 0, s.consumables, &ItemEffectState::consumables)) {
        LS_PROF("items.consumables.on_hit");
        auto [st, eff] = ::lanesim::items::consumables::on_hit(std::move(s.consumables), own, ctx, u, a);
        s.consumables = std::move(st);
        merge_into(out, eff);
    }
    if (run(own, "starters", 1, s.starters, &ItemEffectState::starters)) {
        LS_PROF("items.starters.on_hit");
        auto [st, eff] = ::lanesim::items::starters::on_hit(std::move(s.starters), own, ctx, u, a);
        s.starters = std::move(st);
        merge_into(out, eff);
    }
    if (run(own, "spellblade", 2, s.spellblade, &ItemEffectState::spellblade)) {
        LS_PROF("items.spellblade.on_hit");
        auto [st, eff] = ::lanesim::items::spellblade::on_hit(std::move(s.spellblade), own, ctx, u, a);
        s.spellblade = std::move(st);
        merge_into(out, eff);
    }
    if (run(own, "hydra", 3, s.hydra, &ItemEffectState::hydra)) {
        LS_PROF("items.hydra.on_hit");
        auto [st, eff] = ::lanesim::items::hydra::on_hit(std::move(s.hydra), own, ctx, u, a);
        s.hydra = std::move(st);
        merge_into(out, eff);
    }
    if (run(own, "fighter", 4, s.fighter, &ItemEffectState::fighter)) {
        LS_PROF("items.fighter.on_hit");
        auto [st, eff] = ::lanesim::items::fighter::on_hit(std::move(s.fighter), own, ctx, u, a);
        s.fighter = std::move(st);
        merge_into(out, eff);
    }
    if (run(own, "defense", 5, s.defense, &ItemEffectState::defense)) {
        LS_PROF("items.defense.on_hit");
        auto [st, eff] = ::lanesim::items::defense::on_hit(std::move(s.defense), own, ctx, u, a);
        s.defense = std::move(st);
        merge_into(out, eff);
    }
    if (run(own, "mage", 6, s.mage, &ItemEffectState::mage)) {
        LS_PROF("items.mage.on_hit");
        auto [st, eff] = ::lanesim::items::mage::on_hit(std::move(s.mage), own, ctx, u, a);
        s.mage = std::move(st);
        merge_into(out, eff);
    }
    if (run(own, "marksman", 7, s.marksman, &ItemEffectState::marksman)) {
        LS_PROF("items.marksman.on_hit");
        auto [st, eff] = ::lanesim::items::marksman::on_hit(std::move(s.marksman), own, ctx, u, a);
        s.marksman = std::move(st);
        merge_into(out, eff);
    }
    return out;
}

Effects on_cast(ItemEffectState& s, const Owned& own, const Ctx& ctx, const Units& u, const Cast& cast) {
    LS_PROF("items.on_cast");
    Effects out = no_effects((int)ctx.unit.size(), (int)u.x.size());
    if (run(own, "starters", 1, s.starters, &ItemEffectState::starters)) {
        LS_PROF("items.starters.on_cast");
        auto [st, eff] = ::lanesim::items::starters::on_cast(std::move(s.starters), own, ctx, u, cast);
        s.starters = std::move(st);
        merge_into(out, eff);
    }
    if (run(own, "spellblade", 2, s.spellblade, &ItemEffectState::spellblade)) {
        LS_PROF("items.spellblade.on_cast");
        auto [st, eff] = ::lanesim::items::spellblade::on_cast(std::move(s.spellblade), own, ctx, u, cast);
        s.spellblade = std::move(st);
        merge_into(out, eff);
    }
    if (run(own, "fighter", 4, s.fighter, &ItemEffectState::fighter)) {
        LS_PROF("items.fighter.on_cast");
        auto [st, eff] = ::lanesim::items::fighter::on_cast(std::move(s.fighter), own, ctx, u, cast);
        s.fighter = std::move(st);
        merge_into(out, eff);
    }
    if (run(own, "mage", 6, s.mage, &ItemEffectState::mage)) {
        LS_PROF("items.mage.on_cast");
        auto [st, eff] = ::lanesim::items::mage::on_cast(std::move(s.mage), own, ctx, u, cast);
        s.mage = std::move(st);
        merge_into(out, eff);
    }
    if (run(own, "marksman", 7, s.marksman, &ItemEffectState::marksman)) {
        LS_PROF("items.marksman.on_cast");
        auto [st, eff] = ::lanesim::items::marksman::on_cast(std::move(s.marksman), own, ctx, u, cast);
        s.marksman = std::move(st);
        merge_into(out, eff);
    }
    return out;
}

Effects on_cc(ItemEffectState& s, const Owned& own, const Ctx& ctx, const Units& u, const CC& cc) {
    LS_PROF("items.on_cc");
    Effects out = no_effects((int)ctx.unit.size(), (int)u.x.size());
    if (run(own, "starters", 1, s.starters, &ItemEffectState::starters)) {
        LS_PROF("items.starters.on_cc");
        auto [st, eff] = ::lanesim::items::starters::on_cc(std::move(s.starters), own, ctx, u, cc);
        s.starters = std::move(st);
        merge_into(out, eff);
    }
    return out;
}

Effects on_damage(ItemEffectState& s, const Owned& own, const Ctx& ctx, const Units& u, const Report& r) {
    LS_PROF("items.on_damage");
    Effects out = no_effects((int)ctx.unit.size(), (int)u.x.size());
    if (run(own, "consumables", 0, s.consumables, &ItemEffectState::consumables)) {
        LS_PROF("items.consumables.on_damage");
        auto [st, eff] = ::lanesim::items::consumables::on_damage(std::move(s.consumables), own, ctx, u, r);
        s.consumables = std::move(st);
        merge_into(out, eff);
    }
    if (run(own, "starters", 1, s.starters, &ItemEffectState::starters)) {
        LS_PROF("items.starters.on_damage");
        auto [st, eff] = ::lanesim::items::starters::on_damage(std::move(s.starters), own, ctx, u, r);
        s.starters = std::move(st);
        merge_into(out, eff);
    }
    if (run(own, "fighter", 4, s.fighter, &ItemEffectState::fighter)) {
        LS_PROF("items.fighter.on_damage");
        auto [st, eff] = ::lanesim::items::fighter::on_damage(std::move(s.fighter), own, ctx, u, r);
        s.fighter = std::move(st);
        merge_into(out, eff);
    }
    if (run(own, "defense", 5, s.defense, &ItemEffectState::defense)) {
        LS_PROF("items.defense.on_damage");
        auto [st, eff] = ::lanesim::items::defense::on_damage(std::move(s.defense), own, ctx, u, r);
        s.defense = std::move(st);
        merge_into(out, eff);
    }
    if (run(own, "mage", 6, s.mage, &ItemEffectState::mage)) {
        LS_PROF("items.mage.on_damage");
        auto [st, eff] = ::lanesim::items::mage::on_damage(std::move(s.mage), own, ctx, u, r);
        s.mage = std::move(st);
        merge_into(out, eff);
    }
    if (run(own, "marksman", 7, s.marksman, &ItemEffectState::marksman)) {
        LS_PROF("items.marksman.on_damage");
        auto [st, eff] = ::lanesim::items::marksman::on_damage(std::move(s.marksman), own, ctx, u, r);
        s.marksman = std::move(st);
        merge_into(out, eff);
    }
    if (run(own, "boots", 8, s.boots, &ItemEffectState::boots)) {
        LS_PROF("items.boots.on_damage");
        auto [st, eff] = ::lanesim::items::boots::on_damage(std::move(s.boots), own, ctx, u, r);
        s.boots = std::move(st);
        merge_into(out, eff);
    }
    return out;
}

Effects periodic(ItemEffectState& s, const Owned& own, const Ctx& ctx, const Units& u) {
    LS_PROF("items.periodic");
    Effects out = no_effects((int)ctx.unit.size(), (int)u.x.size());
    if (run(own, "consumables", 0, s.consumables, &ItemEffectState::consumables)) {
        LS_PROF("items.consumables.periodic");
        auto [st, eff] = ::lanesim::items::consumables::periodic(std::move(s.consumables), own, ctx, u);
        s.consumables = std::move(st);
        merge_into(out, eff);
    }
    if (run(own, "starters", 1, s.starters, &ItemEffectState::starters)) {
        LS_PROF("items.starters.periodic");
        auto [st, eff] = ::lanesim::items::starters::periodic(std::move(s.starters), own, ctx, u);
        s.starters = std::move(st);
        merge_into(out, eff);
    }
    if (run(own, "spellblade", 2, s.spellblade, &ItemEffectState::spellblade)) {
        LS_PROF("items.spellblade.periodic");
        auto [st, eff] = ::lanesim::items::spellblade::periodic(std::move(s.spellblade), own, ctx, u);
        s.spellblade = std::move(st);
        merge_into(out, eff);
    }
    if (run(own, "fighter", 4, s.fighter, &ItemEffectState::fighter)) {
        LS_PROF("items.fighter.periodic");
        auto [st, eff] = ::lanesim::items::fighter::periodic(std::move(s.fighter), own, ctx, u);
        s.fighter = std::move(st);
        merge_into(out, eff);
    }
    if (run(own, "defense", 5, s.defense, &ItemEffectState::defense)) {
        LS_PROF("items.defense.periodic");
        auto [st, eff] = ::lanesim::items::defense::periodic(std::move(s.defense), own, ctx, u);
        s.defense = std::move(st);
        merge_into(out, eff);
    }
    if (run(own, "mage", 6, s.mage, &ItemEffectState::mage)) {
        LS_PROF("items.mage.periodic");
        auto [st, eff] = ::lanesim::items::mage::periodic(std::move(s.mage), own, ctx, u);
        s.mage = std::move(st);
        merge_into(out, eff);
    }
    if (run(own, "marksman", 7, s.marksman, &ItemEffectState::marksman)) {
        LS_PROF("items.marksman.periodic");
        auto [st, eff] = ::lanesim::items::marksman::periodic(std::move(s.marksman), own, ctx, u);
        s.marksman = std::move(st);
        merge_into(out, eff);
    }
    if (run(own, "boots", 8, s.boots, &ItemEffectState::boots)) {
        LS_PROF("items.boots.periodic");
        auto [st, eff] = ::lanesim::items::boots::periodic(std::move(s.boots), own, ctx, u);
        s.boots = std::move(st);
        merge_into(out, eff);
    }
    return out;
}

Effects on_takedown(ItemEffectState& s, const Owned& own, const Ctx& ctx, const Units& u, const Kills& k) {
    LS_PROF("items.on_takedown");
    Effects out = no_effects((int)ctx.unit.size(), (int)u.x.size());
    if (run(own, "starters", 1, s.starters, &ItemEffectState::starters)) {
        LS_PROF("items.starters.on_takedown");
        auto [st, eff] = ::lanesim::items::starters::on_takedown(std::move(s.starters), own, ctx, u, k);
        s.starters = std::move(st);
        merge_into(out, eff);
    }
    if (run(own, "fighter", 4, s.fighter, &ItemEffectState::fighter)) {
        LS_PROF("items.fighter.on_takedown");
        auto [st, eff] = ::lanesim::items::fighter::on_takedown(std::move(s.fighter), own, ctx, u, k);
        s.fighter = std::move(st);
        merge_into(out, eff);
    }
    if (run(own, "defense", 5, s.defense, &ItemEffectState::defense)) {
        LS_PROF("items.defense.on_takedown");
        auto [st, eff] = ::lanesim::items::defense::on_takedown(std::move(s.defense), own, ctx, u, k);
        s.defense = std::move(st);
        merge_into(out, eff);
    }
    if (run(own, "mage", 6, s.mage, &ItemEffectState::mage)) {
        LS_PROF("items.mage.on_takedown");
        auto [st, eff] = ::lanesim::items::mage::on_takedown(std::move(s.mage), own, ctx, u, k);
        s.mage = std::move(st);
        merge_into(out, eff);
    }
    if (run(own, "marksman", 7, s.marksman, &ItemEffectState::marksman)) {
        LS_PROF("items.marksman.on_takedown");
        auto [st, eff] = ::lanesim::items::marksman::on_takedown(std::move(s.marksman), own, ctx, u, k);
        s.marksman = std::move(st);
        merge_into(out, eff);
    }
    if (run(own, "boots", 8, s.boots, &ItemEffectState::boots)) {
        LS_PROF("items.boots.on_takedown");
        auto [st, eff] = ::lanesim::items::boots::on_takedown(std::move(s.boots), own, ctx, u, k);
        s.boots = std::move(st);
        merge_into(out, eff);
    }
    return out;
}

Effects active(ItemEffectState& s, const Owned& own, const Ctx& ctx, const Units& u, const Arr<int32_t>& request,
               ActiveOut& out) {
    LS_PROF("items.active");
    size_t c = ctx.unit.size();
    out.used.assign(c, 0), out.cast_time.assign(c, 0.f), out.can_move.assign(c, 1), out.attack_reset.assign(c, 0);
    Effects eff_all = no_effects((int)c, (int)u.x.size());
    if (run(own, "consumables", 0, s.consumables, &ItemEffectState::consumables)) {
        LS_PROF("items.consumables.active");
        auto [st, eff, r] = ::lanesim::items::consumables::active(std::move(s.consumables), own, ctx, u, request);
        s.consumables = std::move(st);
        merge_into(eff_all, eff);
        for (size_t h = 0; h < c; ++h) {
            if (r.used[h]) out.cast_time[h] = r.cast_time[h], out.can_move[h] = r.can_move[h];
            out.used[h] = out.used[h] | r.used[h], out.attack_reset[h] = out.attack_reset[h] | r.attack_reset[h];
        }
    }
    if (run(own, "hydra", 3, s.hydra, &ItemEffectState::hydra)) {
        LS_PROF("items.hydra.active");
        auto [st, eff, r] = ::lanesim::items::hydra::active(std::move(s.hydra), own, ctx, u, request);
        s.hydra = std::move(st);
        merge_into(eff_all, eff);
        for (size_t h = 0; h < c; ++h) {
            if (r.used[h]) out.cast_time[h] = r.cast_time[h], out.can_move[h] = r.can_move[h];
            out.used[h] = out.used[h] | r.used[h], out.attack_reset[h] = out.attack_reset[h] | r.attack_reset[h];
        }
    }
    if (run(own, "actives", 9, s.actives, &ItemEffectState::actives)) {
        LS_PROF("items.actives.active");
        auto [st, eff, r] = ::lanesim::items::actives::active(std::move(s.actives), own, ctx, u, request);
        s.actives = std::move(st);
        merge_into(eff_all, eff);
        for (size_t h = 0; h < c; ++h) {
            if (r.used[h]) out.cast_time[h] = r.cast_time[h], out.can_move[h] = r.can_move[h];
            out.used[h] = out.used[h] | r.used[h], out.attack_reset[h] = out.attack_reset[h] | r.attack_reset[h];
        }
    }
    return eff_all;
}

void on_shop(ItemEffectState& s, const Owned& own, const Ctx& ctx) {
    LS_PROF("items.on_shop");
    if (run(own, "consumables", 0, s.consumables, &ItemEffectState::consumables)) { LS_PROF("items.consumables.on_shop"); s.consumables = ::lanesim::items::consumables::on_shop(std::move(s.consumables), own, ctx); }
}

}  // namespace lanesim::champ::items

namespace lanesim::champ::runes {

namespace {
// Dormant trees, as for items: none of the tree's runes on a page and the state still the initial one.
enum : uint8_t { UNKNOWN, INITIAL, MOVED };
constexpr int N_MODULES = 5;
struct Dormancy {
    const RuneEffectState* initial = nullptr;
    uint8_t mark[N_MODULES] = {};
};
thread_local Dormancy dormancy;
// The tree's rune rows (consts dispatch.runes.<module>), per call-site name literal.
const std::vector<int>& module_rows(const char* name) {
    static thread_local std::unordered_map<const char*, std::vector<int>> cache;
    auto it = cache.find(name);
    if (it != cache.end()) return it->second;
    std::vector<int> rows;
    for (float id : data::table(std::string("dispatch.runes.") + name))
        if (id != 0.f) rows.push_back(rune_row((int)id));
    return cache.emplace(name, std::move(rows)).first->second;
}
template <class S>
bool run(const Arr<int32_t>& page, const char* name, int k, const S& s, S RuneEffectState::*field) {
    LS_PROF("runes.run");
    Dormancy& d = dormancy;
    if (!d.initial) return true;
    static const size_t nr = data::table("runes.ids").size();     // page: (C, runes)
    size_t c = page.size() / nr;
    for (int r : module_rows(name))
        for (size_t h = 0; h < c; ++h)
            if (page[h * nr + r] > 0) return true;
    if (d.mark[k] == UNKNOWN) d.mark[k] = marshal::same_bits(s, d.initial->*field) ? INITIAL : MOVED;
    return d.mark[k] == MOVED;
}
}  // namespace

void set_dormancy(const RuneEffectState* initial) { dormancy = Dormancy{initial, {}}; }

ItemStats stats(const RuneEffectState& s, const Arr<int32_t>& page, const Ctx& ctx, const RuneEvents& ev) {
    LS_PROF("runes.stats");
    ItemStats z = stats::zero(ctx.unit.size());
    std::vector<ItemStats> parts;
    if (run(page, "precision", 0, s.precision, &RuneEffectState::precision)) { LS_PROF("runes.precision.stats"); parts.push_back(::lanesim::runes::precision::stats(s.precision, page, ctx, ev)); }
    if (run(page, "domination", 1, s.domination, &RuneEffectState::domination)) { LS_PROF("runes.domination.stats"); parts.push_back(::lanesim::runes::domination::stats(s.domination, page, ctx, ev)); }
    if (run(page, "sorcery", 2, s.sorcery, &RuneEffectState::sorcery)) { LS_PROF("runes.sorcery.stats"); parts.push_back(::lanesim::runes::sorcery::stats(s.sorcery, page, ctx, ev)); }
    if (run(page, "resolve", 3, s.resolve, &RuneEffectState::resolve)) { LS_PROF("runes.resolve.stats"); parts.push_back(::lanesim::runes::resolve::stats(s.resolve, page, ctx, ev)); }
    if (run(page, "inspiration", 4, s.inspiration, &RuneEffectState::inspiration)) { LS_PROF("runes.inspiration.stats"); parts.push_back(::lanesim::runes::inspiration::stats(s.inspiration, page, ctx, ev)); }
    std::vector<const ItemStats*> ps{&z};
    for (auto& p : parts) ps.push_back(&p);
    return ::lanesim::stats::combine(ps);
}

Debuffs debuffs(const RuneEffectState& s, const Arr<int32_t>& page, const Ctx& ctx, const Units& u, const RuneEvents& ev) {
    LS_PROF("runes.debuffs");
    std::vector<Debuffs> parts;
    std::vector<const Debuffs*> ps;
    for (auto& p : parts) ps.push_back(&p);
    return combine_debuffs(ps, (int)u.x.size());
}

Arr<float> packet_amp(const RuneEffectState& s, const Arr<int32_t>& page, const Ctx& ctx, const Units& u, const RuneEvents& ev,
                    const Packets& p) {
    LS_PROF("runes.packet_amp");
    Arr<float> out(size(p), 0.f);
    if (run(page, "precision", 0, s.precision, &RuneEffectState::precision)) {
        LS_PROF("runes.precision.packet_amp");
        Arr<float> a = ::lanesim::runes::precision::packet_amp(s.precision, page, ctx, u, ev, p);
        for (size_t i = 0; i < out.size(); ++i) out[i] = out[i] + a[i];
    }
    if (run(page, "sorcery", 2, s.sorcery, &RuneEffectState::sorcery)) {
        LS_PROF("runes.sorcery.packet_amp");
        Arr<float> a = ::lanesim::runes::sorcery::packet_amp(s.sorcery, page, ctx, u, ev, p);
        for (size_t i = 0; i < out.size(); ++i) out[i] = out[i] + a[i];
    }
    if (run(page, "inspiration", 4, s.inspiration, &RuneEffectState::inspiration)) {
        LS_PROF("runes.inspiration.packet_amp");
        Arr<float> a = ::lanesim::runes::inspiration::packet_amp(s.inspiration, page, ctx, u, ev, p);
        for (size_t i = 0; i < out.size(); ++i) out[i] = out[i] + a[i];
    }
    return out;
}

Arr<float> packet_block(const RuneEffectState& s, const Arr<int32_t>& page, const Ctx& ctx, const Units& u, const RuneEvents& ev,
                    const Packets& p) {
    LS_PROF("runes.packet_block");
    Arr<float> out(size(p), 0.f);
    if (run(page, "resolve", 3, s.resolve, &RuneEffectState::resolve)) {
        LS_PROF("runes.resolve.packet_block");
        Arr<float> a = ::lanesim::runes::resolve::packet_block(s.resolve, page, ctx, u, ev, p);
        for (size_t i = 0; i < out.size(); ++i) out[i] = out[i] + a[i];
    }
    return out;
}

Arr<float> heal_mult(const RuneEffectState& s, const Arr<int32_t>& page, const Ctx& ctx, const RuneEvents& ev) {
    LS_PROF("runes.heal_mult");
    Arr<float> out(ctx.unit.size(), 1.f);
    if (run(page, "resolve", 3, s.resolve, &RuneEffectState::resolve)) {
        LS_PROF("runes.resolve.heal_mult");
        Arr<float> a = ::lanesim::runes::resolve::heal_mult(s.resolve, page, ctx, ev);
        for (size_t h = 0; h < out.size(); ++h) out[h] = out[h] * a[h];
    }
    return out;
}

Effects on_cast(RuneEffectState& s, const Arr<int32_t>& page, const Ctx& ctx, const Units& u, const RuneEvents& ev) {
    LS_PROF("runes.on_cast");
    Effects out = no_effects((int)ctx.unit.size(), (int)u.x.size());
    if (run(page, "domination", 1, s.domination, &RuneEffectState::domination)) {
        LS_PROF("runes.domination.on_cast");
        auto [st, eff] = ::lanesim::runes::domination::on_cast(std::move(s.domination), page, ctx, u, ev);
        s.domination = std::move(st);
        merge_into(out, eff);
    }
    if (run(page, "sorcery", 2, s.sorcery, &RuneEffectState::sorcery)) {
        LS_PROF("runes.sorcery.on_cast");
        auto [st, eff] = ::lanesim::runes::sorcery::on_cast(std::move(s.sorcery), page, ctx, u, ev);
        s.sorcery = std::move(st);
        merge_into(out, eff);
    }
    if (run(page, "resolve", 3, s.resolve, &RuneEffectState::resolve)) {
        LS_PROF("runes.resolve.on_cast");
        auto [st, eff] = ::lanesim::runes::resolve::on_cast(std::move(s.resolve), page, ctx, u, ev);
        s.resolve = std::move(st);
        merge_into(out, eff);
    }
    return out;
}

Effects on_attack(RuneEffectState& s, const Arr<int32_t>& page, const Ctx& ctx, const Units& u, const RuneEvents& ev) {
    LS_PROF("runes.on_attack");
    Effects out = no_effects((int)ctx.unit.size(), (int)u.x.size());
    if (run(page, "precision", 0, s.precision, &RuneEffectState::precision)) {
        LS_PROF("runes.precision.on_attack");
        auto [st, eff] = ::lanesim::runes::precision::on_attack(std::move(s.precision), page, ctx, u, ev);
        s.precision = std::move(st);
        merge_into(out, eff);
    }
    if (run(page, "domination", 1, s.domination, &RuneEffectState::domination)) {
        LS_PROF("runes.domination.on_attack");
        auto [st, eff] = ::lanesim::runes::domination::on_attack(std::move(s.domination), page, ctx, u, ev);
        s.domination = std::move(st);
        merge_into(out, eff);
    }
    return out;
}

Effects on_hit(RuneEffectState& s, const Arr<int32_t>& page, const Ctx& ctx, const Units& u, const RuneEvents& ev) {
    LS_PROF("runes.on_hit");
    Effects out = no_effects((int)ctx.unit.size(), (int)u.x.size());
    if (run(page, "precision", 0, s.precision, &RuneEffectState::precision)) {
        LS_PROF("runes.precision.on_hit");
        auto [st, eff] = ::lanesim::runes::precision::on_hit(std::move(s.precision), page, ctx, u, ev);
        s.precision = std::move(st);
        merge_into(out, eff);
    }
    if (run(page, "domination", 1, s.domination, &RuneEffectState::domination)) {
        LS_PROF("runes.domination.on_hit");
        auto [st, eff] = ::lanesim::runes::domination::on_hit(std::move(s.domination), page, ctx, u, ev);
        s.domination = std::move(st);
        merge_into(out, eff);
    }
    if (run(page, "resolve", 3, s.resolve, &RuneEffectState::resolve)) {
        LS_PROF("runes.resolve.on_hit");
        auto [st, eff] = ::lanesim::runes::resolve::on_hit(std::move(s.resolve), page, ctx, u, ev);
        s.resolve = std::move(st);
        merge_into(out, eff);
    }
    return out;
}

Effects on_cc(RuneEffectState& s, const Arr<int32_t>& page, const Ctx& ctx, const Units& u, const RuneEvents& ev) {
    LS_PROF("runes.on_cc");
    Effects out = no_effects((int)ctx.unit.size(), (int)u.x.size());
    if (run(page, "domination", 1, s.domination, &RuneEffectState::domination)) {
        LS_PROF("runes.domination.on_cc");
        auto [st, eff] = ::lanesim::runes::domination::on_cc(std::move(s.domination), page, ctx, u, ev);
        s.domination = std::move(st);
        merge_into(out, eff);
    }
    if (run(page, "sorcery", 2, s.sorcery, &RuneEffectState::sorcery)) {
        LS_PROF("runes.sorcery.on_cc");
        auto [st, eff] = ::lanesim::runes::sorcery::on_cc(std::move(s.sorcery), page, ctx, u, ev);
        s.sorcery = std::move(st);
        merge_into(out, eff);
    }
    if (run(page, "resolve", 3, s.resolve, &RuneEffectState::resolve)) {
        LS_PROF("runes.resolve.on_cc");
        auto [st, eff] = ::lanesim::runes::resolve::on_cc(std::move(s.resolve), page, ctx, u, ev);
        s.resolve = std::move(st);
        merge_into(out, eff);
    }
    if (run(page, "inspiration", 4, s.inspiration, &RuneEffectState::inspiration)) {
        LS_PROF("runes.inspiration.on_cc");
        auto [st, eff] = ::lanesim::runes::inspiration::on_cc(std::move(s.inspiration), page, ctx, u, ev);
        s.inspiration = std::move(st);
        merge_into(out, eff);
    }
    return out;
}

Effects periodic(RuneEffectState& s, const Arr<int32_t>& page, const Ctx& ctx, const Units& u, const RuneEvents& ev) {
    LS_PROF("runes.periodic");
    Effects out = no_effects((int)ctx.unit.size(), (int)u.x.size());
    if (run(page, "precision", 0, s.precision, &RuneEffectState::precision)) {
        LS_PROF("runes.precision.periodic");
        auto [st, eff] = ::lanesim::runes::precision::periodic(std::move(s.precision), page, ctx, u, ev);
        s.precision = std::move(st);
        merge_into(out, eff);
    }
    if (run(page, "domination", 1, s.domination, &RuneEffectState::domination)) {
        LS_PROF("runes.domination.periodic");
        auto [st, eff] = ::lanesim::runes::domination::periodic(std::move(s.domination), page, ctx, u, ev);
        s.domination = std::move(st);
        merge_into(out, eff);
    }
    if (run(page, "sorcery", 2, s.sorcery, &RuneEffectState::sorcery)) {
        LS_PROF("runes.sorcery.periodic");
        auto [st, eff] = ::lanesim::runes::sorcery::periodic(std::move(s.sorcery), page, ctx, u, ev);
        s.sorcery = std::move(st);
        merge_into(out, eff);
    }
    if (run(page, "resolve", 3, s.resolve, &RuneEffectState::resolve)) {
        LS_PROF("runes.resolve.periodic");
        auto [st, eff] = ::lanesim::runes::resolve::periodic(std::move(s.resolve), page, ctx, u, ev);
        s.resolve = std::move(st);
        merge_into(out, eff);
    }
    if (run(page, "inspiration", 4, s.inspiration, &RuneEffectState::inspiration)) {
        LS_PROF("runes.inspiration.periodic");
        auto [st, eff] = ::lanesim::runes::inspiration::periodic(std::move(s.inspiration), page, ctx, u, ev);
        s.inspiration = std::move(st);
        merge_into(out, eff);
    }
    return out;
}

Effects on_damage(RuneEffectState& s, const Arr<int32_t>& page, const Ctx& ctx, const Units& u, const RuneEvents& ev) {
    LS_PROF("runes.on_damage");
    Effects out = no_effects((int)ctx.unit.size(), (int)u.x.size());
    if (run(page, "precision", 0, s.precision, &RuneEffectState::precision)) {
        LS_PROF("runes.precision.on_damage");
        auto [st, eff] = ::lanesim::runes::precision::on_damage(std::move(s.precision), page, ctx, u, ev);
        s.precision = std::move(st);
        merge_into(out, eff);
    }
    if (run(page, "domination", 1, s.domination, &RuneEffectState::domination)) {
        LS_PROF("runes.domination.on_damage");
        auto [st, eff] = ::lanesim::runes::domination::on_damage(std::move(s.domination), page, ctx, u, ev);
        s.domination = std::move(st);
        merge_into(out, eff);
    }
    if (run(page, "sorcery", 2, s.sorcery, &RuneEffectState::sorcery)) {
        LS_PROF("runes.sorcery.on_damage");
        auto [st, eff] = ::lanesim::runes::sorcery::on_damage(std::move(s.sorcery), page, ctx, u, ev);
        s.sorcery = std::move(st);
        merge_into(out, eff);
    }
    if (run(page, "resolve", 3, s.resolve, &RuneEffectState::resolve)) {
        LS_PROF("runes.resolve.on_damage");
        auto [st, eff] = ::lanesim::runes::resolve::on_damage(std::move(s.resolve), page, ctx, u, ev);
        s.resolve = std::move(st);
        merge_into(out, eff);
    }
    if (run(page, "inspiration", 4, s.inspiration, &RuneEffectState::inspiration)) {
        LS_PROF("runes.inspiration.on_damage");
        auto [st, eff] = ::lanesim::runes::inspiration::on_damage(std::move(s.inspiration), page, ctx, u, ev);
        s.inspiration = std::move(st);
        merge_into(out, eff);
    }
    return out;
}

Effects on_takedown(RuneEffectState& s, const Arr<int32_t>& page, const Ctx& ctx, const Units& u, const RuneEvents& ev) {
    LS_PROF("runes.on_takedown");
    Effects out = no_effects((int)ctx.unit.size(), (int)u.x.size());
    if (run(page, "precision", 0, s.precision, &RuneEffectState::precision)) {
        LS_PROF("runes.precision.on_takedown");
        auto [st, eff] = ::lanesim::runes::precision::on_takedown(std::move(s.precision), page, ctx, u, ev);
        s.precision = std::move(st);
        merge_into(out, eff);
    }
    if (run(page, "domination", 1, s.domination, &RuneEffectState::domination)) {
        LS_PROF("runes.domination.on_takedown");
        auto [st, eff] = ::lanesim::runes::domination::on_takedown(std::move(s.domination), page, ctx, u, ev);
        s.domination = std::move(st);
        merge_into(out, eff);
    }
    if (run(page, "sorcery", 2, s.sorcery, &RuneEffectState::sorcery)) {
        LS_PROF("runes.sorcery.on_takedown");
        auto [st, eff] = ::lanesim::runes::sorcery::on_takedown(std::move(s.sorcery), page, ctx, u, ev);
        s.sorcery = std::move(st);
        merge_into(out, eff);
    }
    return out;
}

void post_tick(RuneEffectState& s, const Arr<int32_t>& page, const Ctx& ctx, const Units& u, const RuneEvents& ev) {
    LS_PROF("runes.post_tick");
    if (run(page, "resolve", 3, s.resolve, &RuneEffectState::resolve)) { LS_PROF("runes.resolve.post_tick"); s.resolve = ::lanesim::runes::resolve::post_tick(std::move(s.resolve), page, ctx, u, ev); }
    if (run(page, "inspiration", 4, s.inspiration, &RuneEffectState::inspiration)) { LS_PROF("runes.inspiration.post_tick"); s.inspiration = ::lanesim::runes::inspiration::post_tick(std::move(s.inspiration), page, ctx, u, ev); }
}

RuneOutputs outputs(const RuneEffectState& s, const Arr<int32_t>& page, const Ctx& ctx, const RuneEvents& ev) {
    LS_PROF("runes.outputs");
    RuneOutputs out = no_outputs((int)ctx.unit.size(), n_items());
    if (run(page, "sorcery", 2, s.sorcery, &RuneEffectState::sorcery)) { LS_PROF("runes.sorcery.outputs"); merge_outputs_into(out, ::lanesim::runes::sorcery::outputs(s.sorcery, page, ctx, ev)); }
    if (run(page, "inspiration", 4, s.inspiration, &RuneEffectState::inspiration)) { LS_PROF("runes.inspiration.outputs"); merge_outputs_into(out, ::lanesim::runes::inspiration::outputs(s.inspiration, page, ctx, ev)); }
    return out;
}

}  // namespace lanesim::champ::runes

namespace lanesim::champ {
DormancyScope::DormancyScope(const ItemEffectState* items, const RuneEffectState* runes) {
    items::set_dormancy(items), runes::set_dormancy(runes);
}
DormancyScope::~DormancyScope() { items::set_dormancy(nullptr), runes::set_dormancy(nullptr); }
}  // namespace lanesim::champ
