// GENERATED by ops/native/gen_dispatch.py: item and rune dispatch over the ported modules.
#include "dispatch.hpp"

#include "items/items.hpp"
#include "items/items_b.hpp"
#include "runes/runes.hpp"
#include "stats.hpp"

#include <stdexcept>

namespace lanesim::champ::items {

namespace {
// items.effects._each: some holder can hold one of the module's items.
bool live(const Owned& own, const char* name) {
    const auto& ids = data::table(std::string("dispatch.items.") + name);
    if (own.allowed.size() == 0) return true;
    int ni = n_items();
    size_t c = own.allowed.size() / ni;
    for (float id : ids) {
        if (id == 0.f) continue;
        int r = item_row((int)id);
        for (size_t h = 0; h < c; ++h)
            if (own.allowed[h * ni + r]) return true;
    }
    return false;
}
// Item modules with no native port: only worlds where no holder can hold their items are supported.
void check_unported(const Owned& own) {
    if (live(own, "support")) throw std::runtime_error("item module support is not ported (allow-list needed)");
    if (live(own, "jungle")) throw std::runtime_error("item module jungle is not ported (allow-list needed)");
}
}  // namespace

ItemStats dynamic_stats(const ItemEffectState& s, const Owned& own, const Ctx& ctx) {
    check_unported(own);
    ItemStats z = stats::zero(ctx.unit.size());
    std::vector<ItemStats> parts;
    if (live(own, "consumables")) parts.push_back(::lanesim::items::consumables::stats(s.consumables, own, ctx));
    if (live(own, "starters")) parts.push_back(::lanesim::items::starters::stats(s.starters, own, ctx));
    if (live(own, "spellblade")) parts.push_back(::lanesim::items::spellblade::stats(s.spellblade, own, ctx));
    if (live(own, "hydra")) parts.push_back(::lanesim::items::hydra::stats(s.hydra, own, ctx));
    if (live(own, "fighter")) parts.push_back(::lanesim::items::fighter::stats(s.fighter, own, ctx));
    if (live(own, "defense")) parts.push_back(::lanesim::items::defense::stats(s.defense, own, ctx));
    if (live(own, "mage")) parts.push_back(::lanesim::items::mage::stats(s.mage, own, ctx));
    if (live(own, "marksman")) parts.push_back(::lanesim::items::marksman::stats(s.marksman, own, ctx));
    if (live(own, "boots")) parts.push_back(::lanesim::items::boots::stats(s.boots, own, ctx));
    if (live(own, "actives")) parts.push_back(::lanesim::items::actives::stats(s.actives, own, ctx));
    std::vector<const ItemStats*> ps{&z};
    for (auto& p : parts) ps.push_back(&p);
    return stats::combine(ps);
}

HolderDefense holder_defense(const ItemEffectState& s, const Owned& own, const Ctx& ctx) {
    std::vector<HolderDefense> parts;
    if (live(own, "starters")) parts.push_back(::lanesim::items::starters::defense(s.starters, own, ctx));
    if (live(own, "fighter")) parts.push_back(::lanesim::items::fighter::defense(s.fighter, own, ctx));
    if (live(own, "defense")) parts.push_back(::lanesim::items::defense::defense(s.defense, own, ctx));
    if (live(own, "boots")) parts.push_back(::lanesim::items::boots::defense(s.boots, own, ctx));
    std::vector<const HolderDefense*> ps;
    for (auto& p : parts) ps.push_back(&p);
    return combine_defense(ps, (int)ctx.unit.size());
}

StatusFlags status(const ItemEffectState& s, const Owned& own, const Ctx& ctx) {
    StatusFlags out;
    out.ghosted.assign(ctx.unit.size(), 0);
    if (live(own, "marksman")) {
        StatusFlags f = ::lanesim::items::marksman::status(s.marksman, own, ctx);
        for (size_t h = 0; h < out.ghosted.size(); ++h) out.ghosted[h] = out.ghosted[h] | f.ghosted[h];
    }
    if (live(own, "actives")) {
        StatusFlags f = ::lanesim::items::actives::status(s.actives, own, ctx);
        for (size_t h = 0; h < out.ghosted.size(); ++h) out.ghosted[h] = out.ghosted[h] | f.ghosted[h];
    }
    return out;
}

Debuffs target_debuffs(const ItemEffectState& s, const Owned& own, const Ctx& ctx, const Units& u) {
    std::vector<Debuffs> parts;
    if (live(own, "spellblade")) parts.push_back(::lanesim::items::spellblade::debuffs(s.spellblade, own, ctx, u));
    if (live(own, "fighter")) parts.push_back(::lanesim::items::fighter::debuffs(s.fighter, own, ctx, u));
    if (live(own, "defense")) parts.push_back(::lanesim::items::defense::debuffs(s.defense, own, ctx, u));
    if (live(own, "mage")) parts.push_back(::lanesim::items::mage::debuffs(s.mage, own, ctx, u));
    std::vector<const Debuffs*> ps;
    for (auto& p : parts) ps.push_back(&p);
    return combine_debuffs(ps, (int)u.x.size());
}

Arr<float> packet_amp(const ItemEffectState& s, const Owned& own, const Ctx& ctx, const Units& u,
                      const Packets& p) {
    const size_t c = ctx.unit.size(), n = u.x.size(), P = size(p);
    Arr<float> amp(c * n, 0.f);
    if (live(own, "mage")) {
        Arr<float> a = ::lanesim::items::mage::dealt_amp(s.mage, own, ctx, u);
        for (size_t k = 0; k < c * n; ++k) amp[k] = amp[k] + a[k];
    }
    if (live(own, "marksman")) {
        Arr<float> a = ::lanesim::items::marksman::dealt_amp(s.marksman, own, ctx, u);
        for (size_t k = 0; k < c * n; ++k) amp[k] = amp[k] + a[k];
    }
    if (live(own, "boots")) {
        Arr<float> a = ::lanesim::items::boots::dealt_amp(s.boots, own, ctx, u);
        for (size_t k = 0; k < c * n; ++k) amp[k] = amp[k] + a[k];
    }
    Arr<float> out(P, 0.f);
    for (size_t i = 0; i < P; ++i) {
        float sum = 0.f;
        int dst = clampi(p.dst[i], 0, (int)n - 1);
        for (size_t h = 0; h < c; ++h) sum = sum + (p.src[i] == ctx.unit[h] ? amp[h * n + dst] : 0.f);
        out[i] = sum;
    }
    if (live(own, "fighter")) {
        Arr<float> a = ::lanesim::items::fighter::packet_amp(s.fighter, own, ctx, u, p);
        for (size_t i = 0; i < P; ++i) out[i] = out[i] + a[i];
    }
    if (live(own, "marksman")) {
        Arr<float> a = ::lanesim::items::marksman::packet_amp(s.marksman, own, ctx, u, p);
        for (size_t i = 0; i < P; ++i) out[i] = out[i] + a[i];
    }
    if (live(own, "actives")) {
        Arr<float> a = ::lanesim::items::actives::packet_amp(s.actives, own, ctx, u, p);
        for (size_t i = 0; i < P; ++i) out[i] = out[i] + a[i];
    }
    return out;
}

AttackMods attack_mods(const ItemEffectState& s, const Owned& own, const Ctx& ctx, const Units& u,
                       const Arr<int32_t>& target) {
    AttackMods out;
    out.force_crit.assign(ctx.unit.size(), 0), out.crit_scale.assign(ctx.unit.size(), 1.f);
    if (live(own, "fighter")) {
        AttackMods r = ::lanesim::items::fighter::attack_mods(s.fighter, own, ctx, u, target);
        for (size_t h = 0; h < out.force_crit.size(); ++h) {
            if (r.force_crit[h]) out.crit_scale[h] = r.crit_scale[h];
            out.force_crit[h] = out.force_crit[h] | r.force_crit[h];
        }
    }
    if (live(own, "marksman")) {
        AttackMods r = ::lanesim::items::marksman::attack_mods(s.marksman, own, ctx, u, target);
        for (size_t h = 0; h < out.force_crit.size(); ++h) {
            if (r.force_crit[h]) out.crit_scale[h] = r.crit_scale[h];
            out.force_crit[h] = out.force_crit[h] | r.force_crit[h];
        }
    }
    return out;
}

Effects on_attack(ItemEffectState& s, const Owned& own, const Ctx& ctx, const Units& u, const Attack& a) {
    Effects out = no_effects((int)ctx.unit.size(), (int)u.x.size());
    if (live(own, "marksman")) {
        auto [st, eff] = ::lanesim::items::marksman::on_attack(s.marksman, own, ctx, u, a);
        s.marksman = st;
        merge_into(out, eff);
    }
    return out;
}

Effects on_hit(ItemEffectState& s, const Owned& own, const Ctx& ctx, const Units& u, const Attack& a) {
    Effects out = no_effects((int)ctx.unit.size(), (int)u.x.size());
    if (live(own, "consumables")) {
        auto [st, eff] = ::lanesim::items::consumables::on_hit(s.consumables, own, ctx, u, a);
        s.consumables = st;
        merge_into(out, eff);
    }
    if (live(own, "starters")) {
        auto [st, eff] = ::lanesim::items::starters::on_hit(s.starters, own, ctx, u, a);
        s.starters = st;
        merge_into(out, eff);
    }
    if (live(own, "spellblade")) {
        auto [st, eff] = ::lanesim::items::spellblade::on_hit(s.spellblade, own, ctx, u, a);
        s.spellblade = st;
        merge_into(out, eff);
    }
    if (live(own, "hydra")) {
        auto [st, eff] = ::lanesim::items::hydra::on_hit(s.hydra, own, ctx, u, a);
        s.hydra = st;
        merge_into(out, eff);
    }
    if (live(own, "fighter")) {
        auto [st, eff] = ::lanesim::items::fighter::on_hit(s.fighter, own, ctx, u, a);
        s.fighter = st;
        merge_into(out, eff);
    }
    if (live(own, "defense")) {
        auto [st, eff] = ::lanesim::items::defense::on_hit(s.defense, own, ctx, u, a);
        s.defense = st;
        merge_into(out, eff);
    }
    if (live(own, "mage")) {
        auto [st, eff] = ::lanesim::items::mage::on_hit(s.mage, own, ctx, u, a);
        s.mage = st;
        merge_into(out, eff);
    }
    if (live(own, "marksman")) {
        auto [st, eff] = ::lanesim::items::marksman::on_hit(s.marksman, own, ctx, u, a);
        s.marksman = st;
        merge_into(out, eff);
    }
    return out;
}

Effects on_cast(ItemEffectState& s, const Owned& own, const Ctx& ctx, const Units& u, const Cast& cast) {
    Effects out = no_effects((int)ctx.unit.size(), (int)u.x.size());
    if (live(own, "starters")) {
        auto [st, eff] = ::lanesim::items::starters::on_cast(s.starters, own, ctx, u, cast);
        s.starters = st;
        merge_into(out, eff);
    }
    if (live(own, "spellblade")) {
        auto [st, eff] = ::lanesim::items::spellblade::on_cast(s.spellblade, own, ctx, u, cast);
        s.spellblade = st;
        merge_into(out, eff);
    }
    if (live(own, "fighter")) {
        auto [st, eff] = ::lanesim::items::fighter::on_cast(s.fighter, own, ctx, u, cast);
        s.fighter = st;
        merge_into(out, eff);
    }
    if (live(own, "mage")) {
        auto [st, eff] = ::lanesim::items::mage::on_cast(s.mage, own, ctx, u, cast);
        s.mage = st;
        merge_into(out, eff);
    }
    if (live(own, "marksman")) {
        auto [st, eff] = ::lanesim::items::marksman::on_cast(s.marksman, own, ctx, u, cast);
        s.marksman = st;
        merge_into(out, eff);
    }
    return out;
}

Effects on_cc(ItemEffectState& s, const Owned& own, const Ctx& ctx, const Units& u, const CC& cc) {
    Effects out = no_effects((int)ctx.unit.size(), (int)u.x.size());
    if (live(own, "starters")) {
        auto [st, eff] = ::lanesim::items::starters::on_cc(s.starters, own, ctx, u, cc);
        s.starters = st;
        merge_into(out, eff);
    }
    return out;
}

Effects on_damage(ItemEffectState& s, const Owned& own, const Ctx& ctx, const Units& u, const Report& r) {
    Effects out = no_effects((int)ctx.unit.size(), (int)u.x.size());
    if (live(own, "consumables")) {
        auto [st, eff] = ::lanesim::items::consumables::on_damage(s.consumables, own, ctx, u, r);
        s.consumables = st;
        merge_into(out, eff);
    }
    if (live(own, "starters")) {
        auto [st, eff] = ::lanesim::items::starters::on_damage(s.starters, own, ctx, u, r);
        s.starters = st;
        merge_into(out, eff);
    }
    if (live(own, "fighter")) {
        auto [st, eff] = ::lanesim::items::fighter::on_damage(s.fighter, own, ctx, u, r);
        s.fighter = st;
        merge_into(out, eff);
    }
    if (live(own, "defense")) {
        auto [st, eff] = ::lanesim::items::defense::on_damage(s.defense, own, ctx, u, r);
        s.defense = st;
        merge_into(out, eff);
    }
    if (live(own, "mage")) {
        auto [st, eff] = ::lanesim::items::mage::on_damage(s.mage, own, ctx, u, r);
        s.mage = st;
        merge_into(out, eff);
    }
    if (live(own, "marksman")) {
        auto [st, eff] = ::lanesim::items::marksman::on_damage(s.marksman, own, ctx, u, r);
        s.marksman = st;
        merge_into(out, eff);
    }
    if (live(own, "boots")) {
        auto [st, eff] = ::lanesim::items::boots::on_damage(s.boots, own, ctx, u, r);
        s.boots = st;
        merge_into(out, eff);
    }
    return out;
}

Effects periodic(ItemEffectState& s, const Owned& own, const Ctx& ctx, const Units& u) {
    Effects out = no_effects((int)ctx.unit.size(), (int)u.x.size());
    if (live(own, "consumables")) {
        auto [st, eff] = ::lanesim::items::consumables::periodic(s.consumables, own, ctx, u);
        s.consumables = st;
        merge_into(out, eff);
    }
    if (live(own, "starters")) {
        auto [st, eff] = ::lanesim::items::starters::periodic(s.starters, own, ctx, u);
        s.starters = st;
        merge_into(out, eff);
    }
    if (live(own, "spellblade")) {
        auto [st, eff] = ::lanesim::items::spellblade::periodic(s.spellblade, own, ctx, u);
        s.spellblade = st;
        merge_into(out, eff);
    }
    if (live(own, "fighter")) {
        auto [st, eff] = ::lanesim::items::fighter::periodic(s.fighter, own, ctx, u);
        s.fighter = st;
        merge_into(out, eff);
    }
    if (live(own, "defense")) {
        auto [st, eff] = ::lanesim::items::defense::periodic(s.defense, own, ctx, u);
        s.defense = st;
        merge_into(out, eff);
    }
    if (live(own, "mage")) {
        auto [st, eff] = ::lanesim::items::mage::periodic(s.mage, own, ctx, u);
        s.mage = st;
        merge_into(out, eff);
    }
    if (live(own, "marksman")) {
        auto [st, eff] = ::lanesim::items::marksman::periodic(s.marksman, own, ctx, u);
        s.marksman = st;
        merge_into(out, eff);
    }
    if (live(own, "boots")) {
        auto [st, eff] = ::lanesim::items::boots::periodic(s.boots, own, ctx, u);
        s.boots = st;
        merge_into(out, eff);
    }
    return out;
}

Effects on_takedown(ItemEffectState& s, const Owned& own, const Ctx& ctx, const Units& u, const Kills& k) {
    Effects out = no_effects((int)ctx.unit.size(), (int)u.x.size());
    if (live(own, "starters")) {
        auto [st, eff] = ::lanesim::items::starters::on_takedown(s.starters, own, ctx, u, k);
        s.starters = st;
        merge_into(out, eff);
    }
    if (live(own, "fighter")) {
        auto [st, eff] = ::lanesim::items::fighter::on_takedown(s.fighter, own, ctx, u, k);
        s.fighter = st;
        merge_into(out, eff);
    }
    if (live(own, "defense")) {
        auto [st, eff] = ::lanesim::items::defense::on_takedown(s.defense, own, ctx, u, k);
        s.defense = st;
        merge_into(out, eff);
    }
    if (live(own, "mage")) {
        auto [st, eff] = ::lanesim::items::mage::on_takedown(s.mage, own, ctx, u, k);
        s.mage = st;
        merge_into(out, eff);
    }
    if (live(own, "marksman")) {
        auto [st, eff] = ::lanesim::items::marksman::on_takedown(s.marksman, own, ctx, u, k);
        s.marksman = st;
        merge_into(out, eff);
    }
    if (live(own, "boots")) {
        auto [st, eff] = ::lanesim::items::boots::on_takedown(s.boots, own, ctx, u, k);
        s.boots = st;
        merge_into(out, eff);
    }
    return out;
}

Effects active(ItemEffectState& s, const Owned& own, const Ctx& ctx, const Units& u, const Arr<int32_t>& request,
               ActiveOut& out) {
    size_t c = ctx.unit.size();
    out.used.assign(c, 0), out.cast_time.assign(c, 0.f), out.can_move.assign(c, 1), out.attack_reset.assign(c, 0);
    Effects eff_all = no_effects((int)c, (int)u.x.size());
    if (live(own, "consumables")) {
        auto [st, eff, r] = ::lanesim::items::consumables::active(s.consumables, own, ctx, u, request);
        s.consumables = st;
        merge_into(eff_all, eff);
        for (size_t h = 0; h < c; ++h) {
            if (r.used[h]) out.cast_time[h] = r.cast_time[h], out.can_move[h] = r.can_move[h];
            out.used[h] = out.used[h] | r.used[h], out.attack_reset[h] = out.attack_reset[h] | r.attack_reset[h];
        }
    }
    if (live(own, "hydra")) {
        auto [st, eff, r] = ::lanesim::items::hydra::active(s.hydra, own, ctx, u, request);
        s.hydra = st;
        merge_into(eff_all, eff);
        for (size_t h = 0; h < c; ++h) {
            if (r.used[h]) out.cast_time[h] = r.cast_time[h], out.can_move[h] = r.can_move[h];
            out.used[h] = out.used[h] | r.used[h], out.attack_reset[h] = out.attack_reset[h] | r.attack_reset[h];
        }
    }
    if (live(own, "actives")) {
        auto [st, eff, r] = ::lanesim::items::actives::active(s.actives, own, ctx, u, request);
        s.actives = st;
        merge_into(eff_all, eff);
        for (size_t h = 0; h < c; ++h) {
            if (r.used[h]) out.cast_time[h] = r.cast_time[h], out.can_move[h] = r.can_move[h];
            out.used[h] = out.used[h] | r.used[h], out.attack_reset[h] = out.attack_reset[h] | r.attack_reset[h];
        }
    }
    return eff_all;
}

void on_shop(ItemEffectState& s, const Owned& own, const Ctx& ctx) {
    if (live(own, "consumables")) s.consumables = ::lanesim::items::consumables::on_shop(s.consumables, own, ctx);
}

}  // namespace lanesim::champ::items

namespace lanesim::champ::runes {

ItemStats stats(const RuneEffectState& s, const Arr<int32_t>& page, const Ctx& ctx, const RuneEvents& ev) {
    ItemStats z = stats::zero(ctx.unit.size());
    std::vector<ItemStats> parts;
    parts.push_back(::lanesim::runes::precision::stats(s.precision, page, ctx, ev));
    parts.push_back(::lanesim::runes::domination::stats(s.domination, page, ctx, ev));
    parts.push_back(::lanesim::runes::sorcery::stats(s.sorcery, page, ctx, ev));
    parts.push_back(::lanesim::runes::resolve::stats(s.resolve, page, ctx, ev));
    parts.push_back(::lanesim::runes::inspiration::stats(s.inspiration, page, ctx, ev));
    std::vector<const ItemStats*> ps{&z};
    for (auto& p : parts) ps.push_back(&p);
    return ::lanesim::stats::combine(ps);
}

Debuffs debuffs(const RuneEffectState& s, const Arr<int32_t>& page, const Ctx& ctx, const Units& u, const RuneEvents& ev) {
    std::vector<Debuffs> parts;
    std::vector<const Debuffs*> ps;
    for (auto& p : parts) ps.push_back(&p);
    return combine_debuffs(ps, (int)u.x.size());
}

Arr<float> packet_amp(const RuneEffectState& s, const Arr<int32_t>& page, const Ctx& ctx, const Units& u, const RuneEvents& ev,
                    const Packets& p) {
    Arr<float> out(size(p), 0.f);
    {
        Arr<float> a = ::lanesim::runes::precision::packet_amp(s.precision, page, ctx, u, ev, p);
        for (size_t i = 0; i < out.size(); ++i) out[i] = out[i] + a[i];
    }
    {
        Arr<float> a = ::lanesim::runes::sorcery::packet_amp(s.sorcery, page, ctx, u, ev, p);
        for (size_t i = 0; i < out.size(); ++i) out[i] = out[i] + a[i];
    }
    {
        Arr<float> a = ::lanesim::runes::inspiration::packet_amp(s.inspiration, page, ctx, u, ev, p);
        for (size_t i = 0; i < out.size(); ++i) out[i] = out[i] + a[i];
    }
    return out;
}

Arr<float> packet_block(const RuneEffectState& s, const Arr<int32_t>& page, const Ctx& ctx, const Units& u, const RuneEvents& ev,
                    const Packets& p) {
    Arr<float> out(size(p), 0.f);
    {
        Arr<float> a = ::lanesim::runes::resolve::packet_block(s.resolve, page, ctx, u, ev, p);
        for (size_t i = 0; i < out.size(); ++i) out[i] = out[i] + a[i];
    }
    return out;
}

Arr<float> heal_mult(const RuneEffectState& s, const Arr<int32_t>& page, const Ctx& ctx, const RuneEvents& ev) {
    Arr<float> out(ctx.unit.size(), 1.f);
    {
        Arr<float> a = ::lanesim::runes::resolve::heal_mult(s.resolve, page, ctx, ev);
        for (size_t h = 0; h < out.size(); ++h) out[h] = out[h] * a[h];
    }
    return out;
}

Effects on_cast(RuneEffectState& s, const Arr<int32_t>& page, const Ctx& ctx, const Units& u, const RuneEvents& ev) {
    Effects out = no_effects((int)ctx.unit.size(), (int)u.x.size());
    {
        auto [st, eff] = ::lanesim::runes::domination::on_cast(s.domination, page, ctx, u, ev);
        s.domination = st;
        merge_into(out, eff);
    }
    {
        auto [st, eff] = ::lanesim::runes::sorcery::on_cast(s.sorcery, page, ctx, u, ev);
        s.sorcery = st;
        merge_into(out, eff);
    }
    {
        auto [st, eff] = ::lanesim::runes::resolve::on_cast(s.resolve, page, ctx, u, ev);
        s.resolve = st;
        merge_into(out, eff);
    }
    return out;
}

Effects on_attack(RuneEffectState& s, const Arr<int32_t>& page, const Ctx& ctx, const Units& u, const RuneEvents& ev) {
    Effects out = no_effects((int)ctx.unit.size(), (int)u.x.size());
    {
        auto [st, eff] = ::lanesim::runes::precision::on_attack(s.precision, page, ctx, u, ev);
        s.precision = st;
        merge_into(out, eff);
    }
    {
        auto [st, eff] = ::lanesim::runes::domination::on_attack(s.domination, page, ctx, u, ev);
        s.domination = st;
        merge_into(out, eff);
    }
    return out;
}

Effects on_hit(RuneEffectState& s, const Arr<int32_t>& page, const Ctx& ctx, const Units& u, const RuneEvents& ev) {
    Effects out = no_effects((int)ctx.unit.size(), (int)u.x.size());
    {
        auto [st, eff] = ::lanesim::runes::precision::on_hit(s.precision, page, ctx, u, ev);
        s.precision = st;
        merge_into(out, eff);
    }
    {
        auto [st, eff] = ::lanesim::runes::domination::on_hit(s.domination, page, ctx, u, ev);
        s.domination = st;
        merge_into(out, eff);
    }
    {
        auto [st, eff] = ::lanesim::runes::resolve::on_hit(s.resolve, page, ctx, u, ev);
        s.resolve = st;
        merge_into(out, eff);
    }
    return out;
}

Effects on_cc(RuneEffectState& s, const Arr<int32_t>& page, const Ctx& ctx, const Units& u, const RuneEvents& ev) {
    Effects out = no_effects((int)ctx.unit.size(), (int)u.x.size());
    {
        auto [st, eff] = ::lanesim::runes::domination::on_cc(s.domination, page, ctx, u, ev);
        s.domination = st;
        merge_into(out, eff);
    }
    {
        auto [st, eff] = ::lanesim::runes::sorcery::on_cc(s.sorcery, page, ctx, u, ev);
        s.sorcery = st;
        merge_into(out, eff);
    }
    {
        auto [st, eff] = ::lanesim::runes::resolve::on_cc(s.resolve, page, ctx, u, ev);
        s.resolve = st;
        merge_into(out, eff);
    }
    {
        auto [st, eff] = ::lanesim::runes::inspiration::on_cc(s.inspiration, page, ctx, u, ev);
        s.inspiration = st;
        merge_into(out, eff);
    }
    return out;
}

Effects periodic(RuneEffectState& s, const Arr<int32_t>& page, const Ctx& ctx, const Units& u, const RuneEvents& ev) {
    Effects out = no_effects((int)ctx.unit.size(), (int)u.x.size());
    {
        auto [st, eff] = ::lanesim::runes::precision::periodic(s.precision, page, ctx, u, ev);
        s.precision = st;
        merge_into(out, eff);
    }
    {
        auto [st, eff] = ::lanesim::runes::domination::periodic(s.domination, page, ctx, u, ev);
        s.domination = st;
        merge_into(out, eff);
    }
    {
        auto [st, eff] = ::lanesim::runes::sorcery::periodic(s.sorcery, page, ctx, u, ev);
        s.sorcery = st;
        merge_into(out, eff);
    }
    {
        auto [st, eff] = ::lanesim::runes::resolve::periodic(s.resolve, page, ctx, u, ev);
        s.resolve = st;
        merge_into(out, eff);
    }
    {
        auto [st, eff] = ::lanesim::runes::inspiration::periodic(s.inspiration, page, ctx, u, ev);
        s.inspiration = st;
        merge_into(out, eff);
    }
    return out;
}

Effects on_damage(RuneEffectState& s, const Arr<int32_t>& page, const Ctx& ctx, const Units& u, const RuneEvents& ev) {
    Effects out = no_effects((int)ctx.unit.size(), (int)u.x.size());
    {
        auto [st, eff] = ::lanesim::runes::precision::on_damage(s.precision, page, ctx, u, ev);
        s.precision = st;
        merge_into(out, eff);
    }
    {
        auto [st, eff] = ::lanesim::runes::domination::on_damage(s.domination, page, ctx, u, ev);
        s.domination = st;
        merge_into(out, eff);
    }
    {
        auto [st, eff] = ::lanesim::runes::sorcery::on_damage(s.sorcery, page, ctx, u, ev);
        s.sorcery = st;
        merge_into(out, eff);
    }
    {
        auto [st, eff] = ::lanesim::runes::resolve::on_damage(s.resolve, page, ctx, u, ev);
        s.resolve = st;
        merge_into(out, eff);
    }
    {
        auto [st, eff] = ::lanesim::runes::inspiration::on_damage(s.inspiration, page, ctx, u, ev);
        s.inspiration = st;
        merge_into(out, eff);
    }
    return out;
}

Effects on_takedown(RuneEffectState& s, const Arr<int32_t>& page, const Ctx& ctx, const Units& u, const RuneEvents& ev) {
    Effects out = no_effects((int)ctx.unit.size(), (int)u.x.size());
    {
        auto [st, eff] = ::lanesim::runes::precision::on_takedown(s.precision, page, ctx, u, ev);
        s.precision = st;
        merge_into(out, eff);
    }
    {
        auto [st, eff] = ::lanesim::runes::domination::on_takedown(s.domination, page, ctx, u, ev);
        s.domination = st;
        merge_into(out, eff);
    }
    {
        auto [st, eff] = ::lanesim::runes::sorcery::on_takedown(s.sorcery, page, ctx, u, ev);
        s.sorcery = st;
        merge_into(out, eff);
    }
    return out;
}

void post_tick(RuneEffectState& s, const Arr<int32_t>& page, const Ctx& ctx, const Units& u, const RuneEvents& ev) {
    s.resolve = ::lanesim::runes::resolve::post_tick(s.resolve, page, ctx, u, ev);
    s.inspiration = ::lanesim::runes::inspiration::post_tick(s.inspiration, page, ctx, u, ev);
}

RuneOutputs outputs(const RuneEffectState& s, const Arr<int32_t>& page, const Ctx& ctx, const RuneEvents& ev) {
    RuneOutputs out = no_outputs((int)ctx.unit.size(), n_items());
    merge_outputs_into(out, ::lanesim::runes::sorcery::outputs(s.sorcery, page, ctx, ev));
    merge_outputs_into(out, ::lanesim::runes::inspiration::outputs(s.inspiration, page, ctx, ev));
    return out;
}

}  // namespace lanesim::champ::runes
